import {test,afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {APP_VERSION,type Decision,type Session} from '../lib/discovery-contract';
import {validateDecision,seal,unseal,decide} from '../lib/discovery';
import {cardHtml,conversationCard} from '../lib/conversation-card';
import {POST} from '../app/api/discovery/route';
const originalFetch=globalThis.fetch;
const originalEnv={OPENAI_API_KEY:process.env.OPENAI_API_KEY,LLM_API_KEY:process.env.LLM_API_KEY,LLM_MODEL:process.env.LLM_MODEL};
afterEach(()=>{globalThis.fetch=originalFetch;for(const [k,v] of Object.entries(originalEnv)){if(v===undefined)delete process.env[k];else process.env[k]=v;}});
const state=():Session=>({version:APP_VERSION,language:'en',messages:[{role:'user',text:'I heard a voice outside.'}],asked:[],last:null,expires:Date.now()+3600000,accepted:false});
const ask:Decision={decision:'ask',question_id:'Q1',hypothesis:'none',hypothesis_text:'',evidence:[],why_this_question:'untrusted suggestion',stop_type:null,offer_example:false,message:'untrusted suggestion'};
const confirm:Decision={...ask,decision:'confirm',question_id:null,hypothesis:'adhan',evidence:['I heard a voice outside.'],why_this_question:''};
const stop:Decision={...ask,decision:'stop',question_id:null,stop_type:'insufficient_evidence'};
const cfg={apiKey:'test-secret',baseURL:'https://model.invalid/v1',model:'test-model'};
function mock(d:unknown,counter?:()=>void){globalThis.fetch=async()=>{counter?.();return Response.json({model:'test-model',choices:[{finish_reason:'stop',message:{content:JSON.stringify(d)}}]},{headers:{'x-request-id':'mock-only'}});};}
const body=async(r:Response)=>JSON.parse(await r.text());
const req=(body:unknown)=>new Request('https://test.invalid/api/discovery',{method:'POST',body:JSON.stringify(body)});
test('bank wording replaces generated question and rationale',()=>{const d=validateDecision(ask,state());assert.match(d.message,/Where did/);assert.notEqual(d.why_this_question,ask.why_this_question);});
test('unknown and repeated IDs cannot be used',()=>{assert.throws(()=>validateDecision({...ask,question_id:'Q9'},state()));const s=state();s.asked=['Q1'];assert.throws(()=>validateDecision(ask,s));});
test('third clarification question is rejected',()=>{const s=state();s.asked=['Q2','Q3'];assert.throws(()=>validateDecision(ask,s));});
test('fabricated evidence is rejected',()=>assert.throws(()=>validateDecision({...confirm,evidence:['a mosque']},state())));
test('assistant text is not accepted as user evidence',()=>{const s=state();s.messages.push({role:'assistant',text:'a mosque'});assert.throws(()=>validateDecision({...confirm,evidence:['a mosque']},s));});
test('confirmation requires a nonempty evidence quote',()=>assert.throws(()=>validateDecision({...confirm,evidence:[]},state())));
test('stop reason and decision fields are validated',()=>{assert.throws(()=>validateDecision({...stop,stop_type:null},state()));assert.throws(()=>validateDecision({...ask,unexpected:true},state()));});
test('session tokens round-trip and reject tampering and expiry',async()=>{const token=await seal(state(),cfg.apiKey);assert.equal((await unseal(token,cfg.apiKey)).version,APP_VERSION);await assert.rejects(unseal(token+'x',cfg.apiKey));await assert.rejects(unseal(await seal({...state(),expires:0},cfg.apiKey),cfg.apiKey));});
test('every valid discovery call invokes the provider, with strict output and untrusted history',async()=>{let count=0;globalThis.fetch=async(_url,init)=>{const b=JSON.parse(String(init?.body));assert.equal(b.response_format.json_schema.strict,true);assert.equal(b.store,false);assert.equal(b.messages[1].role,'user');assert.ok(!String(init?.body).includes('actual_event'));count++;return Response.json({choices:[{finish_reason:'stop',message:{content:JSON.stringify(ask)}}]});};await decide(state(),cfg);await decide(state(),cfg);assert.equal(count,2);});
test('provider errors and malformed outputs remain technical errors',async()=>{globalThis.fetch=async()=>new Response('',{status:429});await assert.rejects(decide(state(),cfg),/model_limit_reached/);mock({invalid:true});await assert.rejects(decide(state(),cfg),/invalid_model_output/);});
test('missing key returns 503 without a fake decision',async()=>{delete process.env.OPENAI_API_KEY;delete process.env.LLM_API_KEY;const r=await POST(req({action:'start',text:'sound',language:'en'}));assert.equal(r.status,503);const d=await body(r);assert.equal(d.technical,true);assert.equal(d.decision,undefined);});
test('accept without a signed confirmation cannot retrieve explanation',async()=>{process.env.OPENAI_API_KEY=cfg.apiKey;mock(confirm);const r=await POST(req({action:'accept'}));assert.equal(r.status,400);});
test('two model calls create two questions, and a third is rejected',async()=>{process.env.OPENAI_API_KEY=cfg.apiKey;let count=0;mock(ask,()=>count++);const a=await body(await POST(req({action:'start',text:'I heard a voice outside.',language:'en'})));mock({...ask,question_id:'Q3'},()=>count++);const b=await body(await POST(req({action:'reply',text:'not sure',token:a.token})));mock({...ask,question_id:'Q2'},()=>count++);const r=await POST(req({action:'reply',text:'not sure',token:b.token}));assert.equal(r.status,502);assert.equal((await body(r)).error,'invalid_question_choice');assert.equal(count,4);});
test('reject without new detail cannot produce another hypothesis',async()=>{process.env.OPENAI_API_KEY=cfg.apiKey;const s=state();s.last=confirm;const token=await seal(s,cfg.apiKey);mock(confirm);const r=await POST(req({action:'reject',token,text:''}));assert.equal(r.status,502);mock(stop);const valid=await POST(req({action:'reject',token,text:''}));assert.equal(valid.status,200);assert.equal((await body(valid)).decision.decision,'stop');});
test('accepted adhan uses a provider-selected retrieved claim and passing citation gate',async()=>{process.env.OPENAI_API_KEY=cfg.apiKey;const s=state();s.last=confirm;mock({claimIds:['adhan-purpose']});const r=await POST(req({action:'accept',token:await seal(s,cfg.apiKey)}));assert.equal(r.status,200);const d=await body(r);assert.equal(d.result.gate.decision,'Pass');assert.equal(d.result.claims[0].sourceId,'BUK-631');assert.equal((await unseal(d.token,cfg.apiKey)).accepted,true);});
test('an unsupported model-selected claim prevents explanation',async()=>{process.env.OPENAI_API_KEY=cfg.apiKey;const s=state();s.last=confirm;mock({claimIds:['fabricated']});const r=await POST(req({action:'accept',token:await seal(s,cfg.apiKey)}));assert.equal(r.status,502);assert.equal((await body(r)).technical,true);});

test('question-budget violation is repaired by a second real provider call',async()=>{const s=state();s.asked=['Q1','Q3'];let calls=0;globalThis.fetch=async(_u,init)=>{const b=JSON.parse(String(init?.body));assert.deepEqual(b.response_format.json_schema.schema.properties.decision.enum,['confirm','stop']);calls++;return Response.json({choices:[{finish_reason:'stop',message:{content:JSON.stringify(calls===1?ask:stop)}}]});};const d=await decide(s,cfg);assert.equal(d.decision.decision,'stop');assert.equal(calls,2);});
test('Arabic response topic retrieves response evidence and repeated exploration does not exhaust discovery',async()=>{process.env.OPENAI_API_KEY=cfg.apiKey;const s=state();s.language='ar';s.accepted=true;s.last=confirm;let token=await seal(s,cfg.apiKey);globalThis.fetch=async(_u,init)=>{const b=JSON.parse(String(init?.body));const data=JSON.parse(b.messages[1].content);assert.ok(data.evidence.some((x:{claimId:string})=>x.claimId==='adhan-response'));return Response.json({choices:[{message:{content:JSON.stringify({claimIds:['adhan-response']})}}]});};for(let i=0;i<22;i++){const r=await POST(req({action:'explain',topic:'response',text:'كيف يستجيب من يسمعه؟',token}));assert.equal(r.status,200);const d=await body(r);assert.equal(d.result.claims[0].claimId,'adhan-response');token=d.token;}assert.equal((await unseal(token,cfg.apiKey)).messages.length,s.messages.length);});


test('confirmation includes answered pattern before the tentative hypothesis',()=>{const s=state();s.messages=[{role:'user',text:'From a building I heard a sound.'},{role:'user',text:'One voice with phrases and pauses'}];const d=validateDecision({...confirm,evidence:['One voice with phrases and pauses']},s);assert.ok(d.message.indexOf('one voice with phrases and pauses')<d.message.indexOf('may be the adhan'));});
test('a second revision after rejection stops even when new detail is supplied',async()=>{process.env.OPENAI_API_KEY=cfg.apiKey;const s=state();s.last=confirm;s.revisions=1;let calls=0;globalThis.fetch=async(_u,init)=>{const b=JSON.parse(String(init?.body));assert.deepEqual(b.response_format.json_schema.schema.properties.decision.enum,['stop']);calls++;return Response.json({choices:[{finish_reason:'stop',message:{content:JSON.stringify(stop)}}]});};const r=await POST(req({action:'reject',text:'There was music too',token:await seal(s,cfg.apiKey)}));assert.equal(r.status,200);assert.equal((await body(r)).decision.decision,'stop');assert.equal(calls,1);});
test('evidence selection disables response storage and preserves provider request ID',async()=>{process.env.OPENAI_API_KEY=cfg.apiKey;const s=state();s.last=confirm;globalThis.fetch=async(_u,init)=>{assert.equal(JSON.parse(String(init?.body)).store,false);return Response.json({model:'actual-test-model',choices:[{message:{content:JSON.stringify({claimIds:['adhan-purpose']})}}]},{headers:{'x-request-id':'evidence-request'}});};const d=await body(await POST(req({action:'accept',token:await seal(s,cfg.apiKey)})));assert.equal(d.model,'actual-test-model');assert.equal(d.requestId,'evidence-request');});

test('downloadable card escapes visitor markup and deduplicates explored explanations',()=>{const c={id:'test',version:APP_VERSION,promptVersion:'test',language:'en' as const,initialDescription:'<script>alert(1)</script>',startedAt:'2026-10-05',turns:[{at:'test',input:'x',action:'accept',decision:null,displayed:'Explained',model:'test',requestId:null,explanation:'Explained'},{at:'test',input:'x',action:'explain',decision:null,displayed:'Explained',model:'test',requestId:null,explanation:'Explained'}]};const card=conversationCard(c,'<img src=x onerror=alert(1)>','en');assert.equal(card.explanations.length,1);const html=cardHtml(card);assert.ok(!html.includes('<script>'));assert.ok(!html.includes('<img'));assert.ok(html.includes('&lt;script&gt;'));});

test('code gate rejects confirmation for each contrary clue',()=>{for(const extra of ['a car was the source','A short call after a longer call','a group repeating together','continuous recitation','a speech','with music']){const s=state();s.messages=[{role:'user',text:'From a mosque, one voice with phrases and pauses. '+extra}];assert.throws(()=>validateDecision({...confirm,evidence:['one voice with phrases and pauses']},s));}});
test('visual writing cannot offer an adhan example and has stable stop type',()=>{const s=state();s.messages=[{role:'user',text:'رأيت كتابة عربية على مبنى'}];const d=validateDecision({...stop,stop_type:'no_content',offer_example:true},s);assert.equal(d.offer_example,false);assert.equal(d.stop_type,'insufficient_evidence');});
test('recitation cannot offer an adhan example',()=>{const s=state();s.messages=[{role:'user',text:'سمعت رجلا يرتل داخل متجر'}];const d=validateDecision({...stop,stop_type:'out_of_scope',offer_example:true},s);assert.equal(d.offer_example,false);assert.equal(d.stop_type,'insufficient_evidence');});
test('known source prioritizes unknown sound pattern',()=>{const s=state();s.messages=[{role:'user',text:'I heard speakers outside a building'}];assert.throws(()=>validateDecision(ask,s));assert.throws(()=>validateDecision({...ask,question_id:'Q2'},s));assert.equal(validateDecision({...ask,question_id:'Q3'},s).question_id,'Q3');});

test('a moving source alone cannot establish a religious event without content',()=>{const s=state();s.messages=[{role:'user',text:'A van drove down the street with a speaker repeating words.'}];const d=validateDecision({...stop,stop_type:'no_content'},s);assert.equal(d.stop_type,'insufficient_evidence');assert.equal(d.offer_example,false);});
