'use client';
import {useEffect,useRef,useState} from 'react';
import {BookOpen,CalendarDays,Check,Clock3,Download,Globe2,Landmark,MapPin,MessageCircle,Ticket,UserRound,Users} from 'lucide-react';
import {cities} from '@/lib/prayer-clock';
import {TOUR_BOOKINGS,TOUR_DRAFT,bookingDates,confirmBooking,dateLabel,emptyDraft,newBookingId,prototypeNotice,readBookings,readyToBook,ticketHTML,tourById,tourTimes,tours,validDraft,type TourBooking,type TourDraft,type TourLanguage} from '@/lib/tour-booking';

type Stage='list'|'details'|'schedule'|'review'|'ticket'|'tickets';
type Props={language:TourLanguage;city:string;onCityChange:(city:string)=>void;initialQuestion?:string};
export function GuidedTourEntry({language,cityName,onOpen}:{language:TourLanguage;cityName:string;onOpen:()=>void}){
 const t=(ar:string,en:string)=>language==='ar'?ar:en;
 return <section className="tour-entry"><img src="/art/lahza-arch.jpg" alt=""/><div className="tour-entry-copy"><span className="tour-kicker">{cityName} · {t('من الفهم إلى اللقاء','From understanding to meeting')}</span><h2>{t('وراء كل مكان، حكاية.','Every place has a story.')}</h2><p>{t('اكتشفها مع مرشد ديني متخصص، في رحلة تناسب فضولك.','Explore it with a specialist religious guide, on a tour shaped around your curiosity.')}</p><button className="primary" onClick={onOpen}>{t('اختر رحلتك','Choose your tour')}</button><small>{prototypeNotice[language]}</small></div></section>;
}
export default function GuidedTours({language,city,onCityChange,initialQuestion=''}:Props){
 const t=(ar:string,en:string)=>language==='ar'?ar:en;
 const [stage,setStage]=useState<Stage>('list'),[draft,setDraft]=useState<TourDraft>(()=>emptyDraft(language)),[bookings,setBookings]=useState<TourBooking[]>([]),[ticketId,setTicketId]=useState(''),[editing,setEditing]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[ready,setReady]=useState(false);
 const heading=useRef<HTMLHeadingElement|null>(null),dates=bookingDates(),tour=tourById(draft.tourId),ticket=bookings.find(b=>b.id===ticketId),selectedCity=cities.find(c=>c.id===city)||cities[0];
 const storageError=()=>t('تعذّر حفظ الحجز على هذا الجهاز. أبقِ هذه الصفحة مفتوحة، واسمح بالتخزين ثم حاول مجددًا.','Could not save the booking on this device. Keep this page open, allow browser storage, then try again.');
 useEffect(()=>{
  try{
   const saved=readBookings(localStorage.getItem(TOUR_BOOKINGS));setBookings(saved);
   const query=new URLSearchParams(location.search),id=query.get('ticket'),requested=query.get('stage');
   const savedDraft=JSON.parse(localStorage.getItem(TOUR_DRAFT)||'null');
   if(id&&saved.some(b=>b.id===id)){setTicketId(id);setStage('ticket');}
   else if(id||query.get('view')==='ticket'||requested==='tickets')setStage('tickets');
   else if(savedDraft&&validDraft(savedDraft.draft)&&query.get('tour')===savedDraft.draft.tourId&&['details','schedule','review'].includes(requested||'')){
    setDraft(savedDraft.draft);setEditing(saved.some(b=>b.id===savedDraft.draft.id));setStage(requested==='review'&&!readyToBook(savedDraft.draft)?'schedule':requested as Stage);
   }
  }catch{setError(storageError());}
  setReady(true);
 },[]);
 useEffect(()=>{if(ready)heading.current?.focus({preventScroll:true});},[stage,ready]);
 function route(next:Stage,id?:string,d:TourDraft=draft){
  setStage(next);setError('');setNotice('');const q=new URLSearchParams({view:'experiences'});
  if(next==='ticket'&&id)q.set('ticket',id);else if(next!=='list'){q.set('stage',next);if(next!=='tickets'&&d.tourId)q.set('tour',d.tourId);}
  history.replaceState(null,'','/?'+q);window.scrollTo({top:0,behavior:'instant'});
 }
 function saveDraft(next:TourDraft){setDraft(next);try{localStorage.setItem(TOUR_DRAFT,JSON.stringify({draft:next}));return true;}catch{setError(storageError());return false;}}
 function choose(id:string){const next={...emptyDraft(language),id:newBookingId(),tourId:id};setEditing(false);route('details',undefined,next);saveDraft(next);}
 function patch(value:Partial<TourDraft>){setError('');saveDraft({...draft,...value});}
 function finish(){
  if(!readyToBook(draft)){setError(t('اختر يومًا ووقتًا صالحين، وحدد عدد الزوار من 1 إلى 8.','Choose a valid date and time, with 1 to 8 guests.'));return;}
  try{
   const latest=readBookings(localStorage.getItem(TOUR_BOOKINGS)),next=confirmBooking(draft,latest);
   localStorage.setItem(TOUR_BOOKINGS,JSON.stringify(next));setBookings(next);setTicketId(draft.id);setEditing(false);route('ticket',draft.id);
   try{localStorage.removeItem(TOUR_DRAFT);}catch{}
  }catch(e){setError(e instanceof Error&&e.message==='ticket_limit'?t('وصلت إلى 50 تذكرة في هذا النموذج.','This prototype has reached its 50-ticket limit.'):storageError());}
 }
 function editTicket(b:TourBooking){const next={...b,date:dates.includes(b.date)?b.date:''};setEditing(true);route('schedule',undefined,next);saveDraft(next);}
 function cancelTicket(b:TourBooking){
  if(!window.confirm(t('إلغاء هذا الحجز التجريبي؟','Cancel this prototype booking?')))return;
  try{const next=readBookings(localStorage.getItem(TOUR_BOOKINGS)).map(x=>x.id===b.id?{...x,status:'cancelled' as const,updatedAt:new Date().toISOString()}:x);localStorage.setItem(TOUR_BOOKINGS,JSON.stringify(next));setBookings(next);setNotice(t('أُلغي الحجز.','Booking cancelled.'));}catch{setError(storageError());}
 }
 function downloadTicket(b:TourBooking){
  try{const cityName=cities.find(c=>c.id===tourById(b.tourId)?.city)?.[language]||'',file=new Blob([ticketHTML(b,language,cityName)],{type:'text/html;charset=utf-8'}),url=URL.createObjectURL(file),a=document.createElement('a');a.href=url;a.download='lahza-ticket-'+b.id+'.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice(t('أُعدّ ملف التذكرة. افتحه لطباعته أو حفظه PDF.','Your ticket file is ready. Open it to print or save as PDF.'));}catch{setError(t('تعذّر إعداد ملف التذكرة. حاول مرة أخرى.','Could not prepare the ticket file. Please try again.'));}
 }
 function summary(b:TourDraft){const item=tourById(b.tourId);if(!item)return null;const tourCity=cities.find(c=>c.id===item.city);return <dl className="tour-summary"><dt>{t('المدينة والموقع','City and venue')}</dt><dd>{tourCity?.[language]} · {item.place[language]}</dd><dt>{t('الموعد','Date and time')}</dt><dd>{b.date?dateLabel(b.date,language):'…'}<br/><bdi>{b.time} · GMT+3</bdi></dd><dt>{t('المدة','Duration')}</dt><dd>{item.duration} {t('دقيقة','minutes')}</dd><dt>{t('عدد الزوار','Guests')}</dt><dd>{b.guests}</dd><dt>{t('لغة الجولة','Tour language')}</dt><dd>{b.language==='ar'?'العربية':'English'}</dd>{b.name&&<><dt>{t('الاسم على التذكرة','Ticket name')}</dt><dd dir="auto">{b.name}</dd></>}<dt>{t('المرشد','Guide')}</dt><dd>{t('مرشد ديني متخصص','Specialist religious guide')}<small>{item.specialty[language]}</small></dd><dt>{t('نقطة اللقاء المقترحة','Proposed meeting point')}</dt><dd>{item.meeting[language]}</dd>{b.question&&<><dt>{t('سؤالك للمرشد','Your question')}</dt><dd dir="auto">{b.question}</dd></>}</dl>;}
 const titles:Record<Stage,string>={list:t('إلى أين يأخذك فضولك؟','Where will your curiosity take you?'),details:tour?.title[language]||'',schedule:editing?t('عدّل موعد رحلتك','Change your tour date'):t('اختر وقت اللقاء','Choose a time to meet'),review:t('كل تفاصيل رحلتك','Your tour at a glance'),ticket:t('تذكرة رحلتك','Your tour ticket'),tickets:t('تذاكري','My tickets')};
 if(!ready)return <p role="status">{t('جارٍ تجهيز الرحلات…','Getting your tours ready…')}</p>;
 return <div className="guide-flow" data-stage={stage}>
  <div className="tour-toolbar"><span className="badge demo">{t('حجز تجريبي','Booking prototype')}</span>{stage==='list'?<button className="text-button" onClick={()=>route('tickets')}><Ticket size={17}/>{t('تذاكري','My tickets')} ({bookings.filter(b=>b.status==='confirmed').length})</button>:<button className="text-button" onClick={()=>route(stage==='ticket'?'tickets':'list')}>{stage==='ticket'?t('كل تذاكري','All my tickets'):t('كل الرحلات','All tours')}</button>}</div>
  {['details','schedule','review'].includes(stage)&&<ol className="tour-steps" aria-label={t('خطوات الحجز','Booking steps')}>{['details','schedule','review'].map((s,i)=><li key={s} aria-current={stage===s?'step':undefined} className={stage===s?'current':''}><span>{i+1}</span>{[t('الرحلة','Tour'),t('الموعد','Schedule'),t('التأكيد','Confirm')][i]}</li>)}</ol>}
  <h2 className="tour-heading" ref={heading} tabIndex={-1}>{titles[stage]}</h2>
  {stage==='list'&&<><p className="tour-intro">{t('أماكن تكتشفها، وأسئلة تجد من يصغي إليها.','Places to explore. Someone to listen to your questions.')}</p><label htmlFor="tour-city">{t('تجارب مقترحة في','Suggested experiences in')}</label><select id="tour-city" value={city} onChange={e=>onCityChange(e.target.value)}>{cities.map(c=><option key={c.id} value={c.id}>{c[language]}</option>)}</select><p className="tour-city-note"><MapPin size={16}/>{selectedCity[language]} · {t('مع مرشد ديني متخصص','With a specialist religious guide')}</p><div className="tour-catalog">{tours.filter(x=>x.city===city).map((item,i)=><article className={'tour-choice tour-tone-'+i} key={item.id}><div className="tour-choice-top"><span className="tour-category">{item.category==='faith'?<BookOpen size={20}/>:item.category==='history'?<Landmark size={20}/>:<MessageCircle size={20}/>} {item.category==='faith'?t('تجربة دينية','Faith & understanding'):item.category==='history'?t('جولة تاريخية','History'):t('تجربة ثقافية','Culture')}</span><span><Clock3 size={15}/>{item.duration} {t('دقيقة','min')}</span></div><h3>{item.title[language]}</h3><p className="tour-place"><MapPin size={16}/>{item.place[language]}</p><p>{item.description[language]}</p><button className="outlined" onClick={()=>choose(item.id)} aria-label={t('استكشف رحلة: ','Explore tour: ')+item.title[language]}>{t('تفاصيل الرحلة','Explore this tour')}</button></article>)}</div></>}
  {stage==='details'&&tour&&<section className="tour-panel"><div className="tour-detail-art"><img src="/art/lahza-arch.jpg" alt=""/></div><p className="tour-place"><MapPin size={18}/>{tour.place[language]}</p><p>{tour.description[language]}</p><div className="tour-guide"><span><UserRound size={27}/></span><div><strong>{t('برفقة مرشد ديني متخصص','With a specialist religious guide')}</strong><p>{tour.specialty[language]}</p><small>{t('العربية أو الإنجليزية · مساحة لأسئلتك','Arabic or English · Space for your questions')}</small></div></div><h3>{t('مسار اللقاء','Your experience')}</h3><ol className="tour-itinerary">{tour.itinerary.map((stop,i)=><li key={i}><span>{String(i+1).padStart(2,'0')}</span>{stop[language]}</li>)}</ol><div className="tour-meta"><span><Clock3 size={18}/>{tour.duration} {t('دقيقة','minutes')}</span><span><Users size={18}/>1–8 {t('زوار','guests')}</span></div><details className="tour-place-source"><summary>{t('عن المكان','About the place')}</summary><a href={tour.sourceUrl} target="_blank" rel="noopener noreferrer">{t('تعرّف على الموقع من مصدره','Learn about the venue at its source')}</a></details><button className="primary" onClick={()=>route('schedule')}>{t('اختر موعدك','Choose your date')}</button></section>}
  {stage==='schedule'&&tour&&<form className="tour-panel tour-form" onSubmit={e=>{e.preventDefault();if(readyToBook(draft))route('review');else setError(t('اختر يومًا ووقتًا من الخيارات المتاحة.','Choose a date and time from the available options.'));}}><p className="tour-selected-title">{tour.title[language]}</p><label htmlFor="tour-date">{t('اليوم','Day')}</label><select id="tour-date" required value={draft.date} onChange={e=>patch({date:e.target.value})}><option value="">{t('اختر يومًا','Choose a day')}</option>{dates.map(day=><option key={day} value={day}>{dateLabel(day,language)}</option>)}</select><fieldset><legend>{t('الوقت المحلي','Local time')} · GMT+3</legend><div className="tour-slot-options">{tourTimes.map(time=><button className={draft.time===time?'selected':''} aria-pressed={draft.time===time} type="button" key={time} onClick={()=>patch({time})}>{time}</button>)}</div></fieldset><div className="tour-field-pair"><div><label htmlFor="tour-guests">{t('عدد الزوار','Guests')}</label><select id="tour-guests" value={draft.guests} onChange={e=>patch({guests:Number(e.target.value)})}>{Array.from({length:8},(_,i)=><option key={i} value={i+1}>{i+1}</option>)}</select></div><div><label htmlFor="tour-language">{t('لغة الجولة','Tour language')}</label><select id="tour-language" value={draft.language} onChange={e=>patch({language:e.target.value as TourLanguage})}><option value="ar">العربية</option><option value="en">English</option></select></div></div><label htmlFor="tour-name">{t('الاسم على التذكرة (اختياري)','Name on ticket (optional)')}</label><input id="tour-name" autoComplete="given-name" maxLength={80} value={draft.name} onChange={e=>patch({name:e.target.value})}/><label htmlFor="tour-question">{t('سؤال تحمله إلى المرشد (اختياري)','A question for your guide (optional)')}</label><textarea id="tour-question" rows={2} maxLength={300} value={draft.question} onChange={e=>patch({question:e.target.value})}/>{initialQuestion.trim()&&<button className="text-button" type="button" onClick={()=>patch({question:initialQuestion.slice(0,300)})}>{t('استخدم سؤالي من بطاقة الحوار','Use my conversation-card question')}</button>}<div className="tour-form-actions"><button className="primary" type="submit" disabled={!readyToBook(draft)}>{t('راجع الحجز','Review booking')}</button><button className="text-button" type="button" onClick={()=>{if(editing&&bookings.some(b=>b.id===draft.id)){setTicketId(draft.id);route('ticket',draft.id);}else route('details');}}>{t('رجوع','Back')}</button></div></form>}
  {stage==='review'&&tour&&<section className="tour-panel"><h3>{tour.title[language]}</h3>{summary(draft)}<p className="tour-no-payment">{t('لا يتطلب النموذج أي دفع.','No payment is required in this prototype.')}</p><button className="primary" onClick={finish}>{editing?t('احفظ تعديل الحجز','Save booking changes'):t('أكّد الحجز وأصدر التذكرة','Confirm booking & get ticket')}</button><button className="text-button tour-full" onClick={()=>route('schedule')}>{t('تعديل التفاصيل','Edit details')}</button></section>}
  {stage==='ticket'&&ticket&&<><article className={'guide-ticket '+(ticket.status==='cancelled'?'is-cancelled':'')}><header><span className="tour-kicker">لَحْظَة | LAHZA</span><span className="badge demo">{t('تذكرة تجريبية','Prototype ticket')}</span><div className="tour-ticket-symbol"><Check size={28}/></div><p>{ticket.status==='cancelled'?t('الحجز ملغى','Booking cancelled'):t('رحلتك بانتظار فضولك','Your next discovery awaits')}</p><h3>{tourById(ticket.tourId)?.title[language]}</h3><span className="tour-ticket-status">{ticket.status==='cancelled'?t('ملغى','Cancelled'):t('تم تأكيد الحجز التجريبي','Prototype booking confirmed')}</span></header><div className="guide-ticket-body"><div className="tour-booking-code"><span>{t('رقم الحجز','Booking reference')}</span><strong dir="ltr">{ticket.id}</strong></div>{summary(ticket)}</div><footer><Ticket size={20}/><p>{prototypeNotice[language]} {t('هذه ليست تذكرة دخول فعلية.','This is not an admission ticket.')}</p></footer></article><div className="tour-ticket-actions"><button className="primary" onClick={()=>downloadTicket(ticket)}><Download size={19}/>{t('نزّل التذكرة','Download ticket')}</button>{ticket.status==='confirmed'&&<div className="tour-action-pair"><button className="outlined" onClick={()=>editTicket(ticket)}>{t('عدّل الموعد','Change date')}</button><button className="text-button" onClick={()=>cancelTicket(ticket)}>{t('إلغاء الحجز','Cancel booking')}</button></div>}<button className="text-button tour-full" onClick={()=>route('list')}>{t('اكتشف رحلة أخرى','Discover another tour')}</button></div><p className="fine-print">{t('تذكرتك محفوظة على هذا الجهاز.','Your ticket is saved on this device.')}</p></>}
  {stage==='tickets'&&<div className="tour-saved-list">{bookings.length?bookings.map(b=><button className="tour-saved-ticket" key={b.id} onClick={()=>{setTicketId(b.id);route('ticket',b.id);}}><Ticket size={24}/><span><strong>{tourById(b.tourId)?.title[language]}</strong><small>{dateLabel(b.date,language)} · {b.time}</small><bdi>{b.id}</bdi></span><span className={'badge '+(b.status==='confirmed'?'demo':'')}>{b.status==='confirmed'?t('تجريبية','Prototype'):t('ملغاة','Cancelled')}</span></button>):<section className="tour-panel tour-empty"><Ticket size={38}/><h3>{t('رحلتك الأولى تنتظرك','Your first tour awaits')}</h3><p>{t('اختر تجربة، وستجد تذكرتها هنا بعد التأكيد.','Choose an experience. Its ticket will appear here after confirmation.')}</p><button className="primary" onClick={()=>route('list')}>{t('استعرض الرحلات','Browse tours')}</button></section>}</div>}
  {error&&<div className="error-state" role="alert">{error}</div>}{notice&&<p className="tour-notice" role="status">{notice}</p>}
  {stage!=='ticket'&&<p className="tour-prototype-note">{prototypeNotice[language]} {t('المواعيد والمرشدون ونقاط اللقاء ضمن سيناريو العرض.','Schedules, guides and meeting points are part of the demo scenario.')}</p>}
 </div>;
}
