'use client';
import {useEffect,useRef,useState} from 'react';
import {Compass,Globe2,BookOpen,ShieldCheck,Download,RotateCcw,MessageCircle} from 'lucide-react';
import {APP_VERSION,PROMPT_VERSION,type Conversation,type Decision,type Lang,type Turn} from '@/lib/discovery-contract';
import {downloadJson,saveConversation} from '@/lib/conversation-log';
import {preferredLanguage,saveLanguage} from '@/lib/language-preference';
import {conversationCard,downloadCard,type JourneyCard} from '@/lib/conversation-card';
import approvedTopics from '@/lib/approved-topics.json';
import type {Result} from '@/lib/agent';
type ApiResponse = {token:string;askedCount:number;model:string;requestId:string|null;error?:string} & ({kind:'explanation';result:Result}|{kind:'decision';decision:Decision});
export default function LahzaDiscovery(){
 const [lang,setLang]=useState<Lang>('ar'),[text,setText]=useState(''),[token,setToken]=useState(''),[decision,setDecision]=useState<Decision|null>(null),[result,setResult]=useState<Result|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[configured,setConfigured]=useState<boolean|null>(null),[storageError,setStorageError]=useState(false),[topic,setTopic]=useState('purpose'),[depth,setDepth]=useState('10'),[example,setExample]=useState(false),[count,setCount]=useState(0);
 const [card,setCard]=useState<JourneyCard|null>(null);const cardDialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(card&&!cardDialog.current?.open)cardDialog.current?.showModal();},[card]);
 const conversation=useRef<Conversation|null>(null),pending=useRef(false);
 const ar=lang==='ar';const t=(a:string,e:string)=>ar?a:e;
 useEffect(()=>{setLang(preferredLanguage());},[]);
 useEffect(()=>{document.documentElement.lang=lang;document.documentElement.dir=ar?'rtl':'ltr';},[lang,ar]);
 useEffect(()=>{fetch('/api/health').then(r=>r.json() as Promise<{discoveryModelConfigured:boolean}>).then(h=>setConfigured(h.discoveryModelConfigured===true)).catch(()=>setConfigured(null));},[]);
 function reset(){setText('');setToken('');setDecision(null);setResult(null);setError('');setExample(false);setCount(0);setTopic('purpose');setDepth('10');setCard(null);setStorageError(false);conversation.current=null;}
 function record(turn:Turn){const c=conversation.current;if(!c)return;c.turns.push(turn);if(!saveConversation(c))setStorageError(true);}
 function errorText(code:string){if(code==='content_not_approved')return t('هذا الفرع غير متاح حتى اعتماد محتواه.','This topic is unavailable until its content is approved.');if(code==='session_limit')return t('وصلت رحلة الاكتشاف إلى حدها. يمكنك بدء لحظة جديدة وتنزيل السجل.','This discovery journey has reached its limit. Start a new moment or download its transcript.');if(code==='evidence_unavailable')return t('لم يُعثر على دليل كافٍ لهذا الشرح. يمكنك اختيار جانب آخر أو إعادة المحاولة.','Not enough evidence was selected for this explanation. Choose another topic or retry.');return code==='model_not_configured'?t('خدمة الاكتشاف الذكي لم تُفعّل بعد. لم يُرسل وصفك إلى نموذج، ولم نحدّد اللحظة.','AI discovery is not activated yet. Your description was not sent to a model and no identification was made.'):code==='session_expired'?t('انتهت صلاحية هذه الرحلة. ابدأ لحظة جديدة؛ السجل متاح في صفحة رحلاتي.','This journey has expired. Start a new moment; the transcript is available in My journeys.'):t('تعذّر إكمال استدعاء النموذج أو التحقق من مخرجه. هذا عطل تقني، وليس حكمًا على وصفك. يمكنك إعادة المحاولة.','The model call or output validation failed. This is a technical error, not a judgment about your description. You can retry.');}
 async function send(action:string,input=text,chosenTopic=topic,chosenDepth=depth){
  if(pending.current)return;pending.current=true;setBusy(true);setError('');
  if(action==='start'){conversation.current={id:crypto.randomUUID(),version:APP_VERSION,promptVersion:PROMPT_VERSION,language:lang,initialDescription:input,startedAt:new Date().toISOString(),turns:[]};setResult(null);setExample(false);}
  const at=new Date().toISOString();
  try{const res=await fetch('/api/discovery',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,text:input,language:lang,token,topic:chosenTopic,depth:chosenDepth})});const d=await res.json() as ApiResponse;
   if(!res.ok){const code=d.error||'request_failed';record({at,input,action,decision:null,displayed:errorText(code),error:code,model:null,requestId:null});setError(errorText(code));return;}
   setToken(d.token);setCount(d.askedCount);setText('');setTopic(chosenTopic);setDepth(chosenDepth);
   if(d.kind==='explanation'){setResult(d.result);setDecision(null);record({at,input,action,decision:null,displayed:d.result.answer,explanation:d.result.answer,sources:d.result.claims.map((c:{sourceId:string;url:string})=>({id:c.sourceId,url:c.url})),model:d.model,requestId:d.requestId});}
   else{setDecision(d.decision);setResult(null);record({at,input,action,decision:d.decision,displayed:d.decision.message+(d.decision.why_this_question?'\n'+d.decision.why_this_question:''),model:d.model,requestId:d.requestId});}
  }catch{const code='network_error';setError(errorText(code));record({at,input,action,decision:null,displayed:errorText(code),error:code,model:null,requestId:null});}
  finally{setBusy(false);pending.current=false;}
 }
 async function exploreExample(){if(pending.current)return;pending.current=true;setBusy(true);setError('');const q=t('ما هو الأذان؟','What is the adhan?');if(!conversation.current)conversation.current={id:crypto.randomUUID(),version:APP_VERSION,promptVersion:PROMPT_VERSION,language:lang,initialDescription:t('استكشاف الأذان كمثال تعليمي','Explore the adhan as an educational example'),startedAt:new Date().toISOString(),turns:[]};try{const r=await fetch('/api/journey',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q,language:lang,depth:'10',confirmed:true})});if(!r.ok)throw Error();const d=await r.json() as Result;setResult(d);setDecision(null);setExample(true);record({at:new Date().toISOString(),input:q,action:'explicit_example',decision:null,displayed:d.answer,explanation:d.answer,sources:d.claims.map(c=>({id:c.sourceId,url:c.url})),model:null,requestId:null});}catch{setError(t('تعذّر فتح المثال.','The example could not be opened.'));}finally{setBusy(false);pending.current=false;}}
 function handoff(){const c=conversation.current;if(c)setCard(conversationCard(c,text,lang));}
 const choices:Record<string,string[]>={Q1:ar?['مكبرات خارج مبنى','داخل المكان','هاتف أو جهاز']:['Speakers outside a building','Inside the place','A phone or device'],Q2:ar?['أقل من دقيقة','دقائق قليلة','أطول بكثير']:['Under a minute','A few minutes','Much longer'],Q3:ar?['عبارات منغّمة بينها وقفات','قراءة متصلة','حديث كالخطاب','جماعة تكرر عبارة']:['Melodic phrases with pauses','Continuous reciting','A speech','A group repeating a phrase'],Q5:ar?['نعم، سمعت نداءً أطول قبله','لا، لم أسمع']:['Yes, I heard a longer call earlier','No, I did not hear one'],Q6:ar?['نعم','لا']:['Yes','No'],Q7:ar?['اتجهوا إلى مبنى','وقفوا صفوفًا','واصلوا شأنهم']:['Walked towards a building','Stood in rows','Carried on'],Q8:ar?['وقوف في صفوف وانحناء معًا','جلوس واستماع لمتحدث','شخص يقرأ من كتاب']:['Standing in rows and bowing together','Sitting and listening to a speaker','One person reading a book']};

 return <main dir={ar?'rtl':'ltr'} lang={lang}>
 <header><a className="brand" href="/"><span className="brand-symbol"><Compass/></span><span>لَحْظَة <small>LAHZA</small></span></a><nav className="header-links" aria-label={t('التنقل','Navigation')}><a href="/judge">{t('رحلاتي وأثر السؤال','My journeys and question impact')}</a></nav><label className="language language-picker" title={conversation.current?t('ابدأ لحظة جديدة لتغيير لغة الرحلة','Start a new moment to change the journey language'):t('لغة التجربة','Experience language')}><Globe2 size={17}/><select aria-label={t('لغة التجربة','Experience language')} disabled={busy||!!conversation.current} value={lang} onChange={e=>{const language=e.target.value as Lang;setLang(language);saveLanguage(language);}}><option value="ar">العربية</option><option value="en">English</option></select></label></header>
 <div className="discovery-stage"><div className="shell">
 <aside className="intro" dir={ar?'rtl':'ltr'}><img className="reference-scene" src="/art/lahza-arch.jpg" alt={t('زائر يتحاور مع سفير ثقافي في فناء','A visitor and a cultural ambassador in a courtyard')}/><div className="intro-copy"><div className="eyebrow">{t('كل رحلة تبدأ بلحظة','Every journey begins with a moment')}</div><h1>{t('لا تعرف ماذا تسأل؟','Not sure what to ask?')}<br/><em>{t('ابدأ بما لاحظت.','Start with what you noticed.')}</em></h1><p className="lead">{t('لَحْظَة تساعدك على فهم ما أثار فضولك، حتى عندما لا تعرف ماذا تسأل.','LAHZA helps you understand what sparked your curiosity, even when you don’t know what to ask.')}</p><div className="journey-map"><span className="active">{t('صِف اللحظة','Describe')}</span><span>{t('اكتشف السؤال','Discover')}</span><span>{t('افهم بالدليل','Understand')}</span></div></div></aside>
 <section className="workspace" dir={ar?'rtl':'ltr'} aria-label={t('اكتشاف اللحظة','Discover a moment')}>
 <div className="card-top"><span className="moment"><Compass size={18}/>{t('اكتشاف اللحظة','Discover a moment')}</span><span className="edition">{t('بكلماتك','In your words')}</span></div>
 {conversation.current&&<details className="moment-recap"><summary>{t('اللحظة التي وصفتها','The moment you described')}</summary><p dir="auto">{conversation.current.initialDescription}</p></details>}
 {configured===false&&<p className="service-notice" role="status">{t('الاكتشاف الذكي غير متاح حاليًا. يمكنك استكشاف شرح الأذان من المصادر أدناه.','AI discovery is currently unavailable. You can explore the source-based adhan explanation below.')}</p>}
 {!decision&&!result&&<div className="start"><h2>{t('ما الذي لفت انتباهك؟','What caught your attention?')}</h2><p>{t('صف ما رأيته أو سمعته بكلماتك. لا تحتاج إلى معرفة اسمه.','Describe what you saw or heard in your own words. You don’t need to know its name.')}</p></div>}
 {decision&&<div className="result" aria-live="polite"><div className="result-meta"><span>{t('أسئلة الاستيضاح','Clarification questions')}: {count}/2</span></div><h2>{decision.decision==='ask'?t('لنقترب من اللحظة','Let’s understand the moment'):decision.decision==='confirm'?t('هل هذا ما تقصده؟','Is this what you mean?'):t('حدود ما نعرفه','What we can establish')}</h2><p className="answer">{decision.message}</p>
 {decision.decision==='ask'&&<div className="why-question"><strong>{t('لماذا أسألك هذا؟','Why am I asking?')}</strong><p>{decision.why_this_question}</p></div>}
 {decision.decision==='confirm'&&<><div className="evidence-clues"><strong>{t('ما الذي بنيت عليه','The clues you shared')}</strong>{decision.evidence.map((e,i)=><blockquote key={i}>{e}</blockquote>)}</div><div className="confirmation"><button disabled={busy} className="primary" onClick={()=>send('accept',t('نعم، أريد استكشاف الأذان','Yes, I want to explore the adhan'))}>{t('نعم، أريد فهم الأذان','Yes, explain the adhan')}</button><button disabled={busy} onClick={()=>send('unsure',t('لست متأكدًا','I’m not sure'))}>{t('لست متأكدًا','I’m not sure')}</button><button disabled={busy} onClick={()=>send('reject','')}>{t('لا شيء من هذه / ليس ما أقصده','None of these / not what I meant')}</button></div><label className="correction-label" htmlFor="correction">{t('هل لديك تفصيل يصحح الاحتمال؟ اختياري','Another detail to correct the suggestion? Optional')}</label><textarea disabled={busy} id="correction" maxLength={1200} rows={2} value={text} onChange={e=>setText(e.target.value)}/><button disabled={busy||!text.trim()} onClick={()=>send('reject',text)}>{t('لا، وإليك تفصيلًا آخر','No, here is another detail')}</button></>}
 {decision.decision==='stop'&&decision.offer_example&&<button disabled={busy} onClick={exploreExample}>{t('استكشف الأذان كمثال فقط','Explore the adhan as an example only')}</button>}
 </div>}
 {result&&<div className="result" aria-live="polite">{example&&<p className="service-notice">{t('مثال تعليمي اخترته؛ لم نحدّد الصوت الذي سمعته.','An example you chose; the sound you heard has not been identified.')}</p>}<div className="result-meta"><span><BookOpen size={16}/>{t('شرح مستند إلى مصدر','Source-based explanation')}</span><span><ShieldCheck size={16}/>{t('مصادر قابلة للتتبع','Traceable sources')}</span></div><h2>{topic==='words'?t('ما وراء الكلمات','Understanding the words'):topic==='response'?t('كيف يستجيب المستمع؟','How do listeners respond?'):t('نداء إلى الصلاة','A call to prayer')}</h2><p className="answer">{result.answer}</p>
 {!example&&<div className="topic-tabs" role="group" aria-label={t('اختر ما يثير اهتمامك','Choose what interests you')}>{[['purpose',t('النداء','The call')],['words',t('الكلمات','The words')],['response',t('الاستجابة','The response')],...([['why',t('لماذا يوجد الأذان؟','Why does it exist?')],['origin',t('كيف بدأ؟','How did it begin?')],['after',t('ماذا يحدث بعد النداء؟','What happens afterwards?')],['phrase_meanings',t('معاني العبارات','Phrase meanings')]].filter(([id])=>(approvedTopics as string[]).includes(id)))].map(([id,label])=><button disabled={busy} aria-pressed={topic===id} key={id} className={topic===id?'selected':''} onClick={()=>{if(topic!==id)send('explain',label,id,'30');}}>{label}</button>)}</div>}
 <details className="sources"><summary><BookOpen size={18}/>{t('ما الدليل على هذه المعلومة؟','What supports this explanation?')}</summary>{result.claims.map(c=>{const source=result.passages.find(p=>p.source.id===c.sourceId)?.source;return <div className="source" key={c.claimId}><p>{c.text}</p><a href={c.url} target="_blank" rel="noreferrer">{c.sourceId} · {source?.reference}</a><blockquote dir="rtl">{source?.original}</blockquote></div>;})}<p className="review">{t('المراجعة العلمية واللغوية البشرية معلّقة. الشرح الإنجليزي إعادة صياغة، وليس ترجمة معتمدة.','Human scholarly and language review is pending. English text is a paraphrase, not a certified translation.')}</p></details>

 </div>}
 {(!decision&&!result||decision?.decision==='ask')&&<form className="input-area" onSubmit={e=>{e.preventDefault();send(decision?'reply':'start');}}><div className="quick-answers">{decision?.decision==='ask'&&(choices[decision.question_id||'']||[]).map(answer=><button type="button" disabled={busy} key={answer} onClick={()=>send('reply',answer)}>{answer}</button>)}</div><label htmlFor="description">{decision?t('أو أضف إجابتك بكلماتك','Or answer in your own words'):t('اكتب وصفك','Your description')}</label><textarea disabled={busy} id="description" rows={3} maxLength={1200} value={text} onChange={e=>setText(e.target.value)} placeholder={t('رأيت… سمعت…','I saw… I heard…')}/><div className="input-tools">{decision&&<button type="button" disabled={busy} onClick={()=>send('reply',t('لا أعرف','I’m not sure'))}>{t('لا أعرف','I’m not sure')}</button>}<button className="primary" disabled={busy||!text.trim()}>{busy?t('جارٍ الاتصال…','Connecting…'):(decision?t('تابع الاكتشاف','Continue'):t('اكتشف اللحظة','Discover the moment'))}</button></div></form>}
 {!decision&&!result&&<details className="discovery-options"><summary>{t('تحتاج إلى بداية؟','Need a starting point?')}</summary><button type="button" disabled={busy} className="sample" onClick={()=>{const v=t('سمعت صوتًا بالعربية في مكان عام','I heard a voice in Arabic in a public place');setText(v);document.getElementById('description')?.focus();}}>{t('سمعت صوتًا بالعربية في مكان عام','I heard a voice in Arabic in a public place')}</button></details>}
 {busy&&<p className="status-line" role="status">{t('نتأمل وصفك…','Looking at your description…')}</p>}
 {error&&<p role="alert" className="error status-line">{error}</p>}
 {storageError&&<p role="alert" className="error status-line">{t('تعذّر حفظ السجل في المتصفح. نزّله الآن قبل مغادرة الصفحة.','Browser storage failed. Download the transcript before leaving.')}</p>}
 {conversation.current&&<div className="session-actions">{decision?.stop_type!=='out_of_scope'&&<button disabled={busy} onClick={handoff}><MessageCircle size={17}/>{t('بطاقة للحوار','Conversation card')}</button>}<button disabled={busy} onClick={()=>downloadJson(conversation.current,'lahza-transcript.json')}><Download size={17}/>{t('تنزيل السجل','Download transcript')}</button><button disabled={busy} onClick={reset}><RotateCcw size={17}/>{t('لحظة جديدة','New moment')}</button>{decision?.stop_type!=='out_of_scope'&&<small>{t('عاين بطاقة يمكنك حفظها أو مشاركتها بنفسك. لا تُرسل تلقائيًا.','Preview a card you can save or share yourself. No message is sent.')}</small>}</div>}
 <details className="privacy-details"><summary>{t('خصوصيتك وسجل رحلتك','Your privacy and journey history')}</summary><p className="privacy-note">{t('لا حساب ولا طلب للموقع. يُحفظ اختيار اللغة على هذا الجهاز. عند استخدام الاكتشاف الذكي، يُرسل وصفك وإجاباتك إلى خدمة ذكاء اصطناعي لمعالجتها. يُحفظ نص الحوار مؤقتًا في هذا التبويب لآخر 20 رحلة، ويمكن تنزيله أو حذفه من صفحة رحلاتي. قد تحتفظ البنية التحتية ومزوّد النموذج بسجلات وفق إعداداتهما.','No account or location request. Your language preference is saved on this device. When you use AI discovery, your description and replies are sent to an AI service for processing. Transcripts of the last 20 journeys are kept temporarily in this tab; download or delete them in My journeys. Infrastructure and model providers may retain logs according to their settings.')}</p></details>
 </section></div></div><footer><span>لَحْظَة · LAHZA v{APP_VERSION}</span><a href="/judge">{t('رحلاتي وسجل الحوار','My journeys and transcripts')}</a><a href={`/downloads/lahza-source-v${APP_VERSION}.zip`}>{t('تنزيل الكود','Download source')}</a><a href="/about">{t('عن لحظة ومصادرها','About LAHZA and its sources')}</a><a href="https://icons8.com/illustrations" target="_blank" rel="noreferrer">Illustrations by Icons8 Ouch</a></footer>
 <dialog ref={cardDialog} className="journey-card-dialog" onClose={()=>setCard(null)} aria-labelledby="card-title">{card&&<><div className="card-toolbar"><button onClick={()=>cardDialog.current?.close()}>{t('إغلاق','Close')}</button><button className="primary" onClick={()=>downloadCard(card)}>{t('حفظ البطاقة','Save card')}</button><button onClick={()=>window.print()}>{t('طباعة / PDF','Print / PDF')}</button></div><small>لَحْظَة · LAHZA v{card.version}</small><h2 id="card-title">{card.title}</h2><h3>{t('ما لاحظته','What I noticed')}</h3><p dir="auto">{card.moment}</p><h3>{t('ما استكشفته','What I explored')}</h3>{card.explanations.length?card.explanations.map((x,i)=><p key={i}>{x}</p>):<p>{t('لم تستكشف شرحًا بعد. يمكنك الاحتفاظ بوصفك وسؤالك.','No explanation explored yet. You can keep your description and question.')}</p>}<label htmlFor="card-question">{t('سؤالي للحوار، يمكنك تعديله','My question for a conversation, editable')}</label><textarea id="card-question" maxLength={1200} value={card.question} onChange={e=>setCard({...card,question:e.target.value})}/><p className="print-question">{card.question}</p><h3>{t('المصادر','Sources')}</h3>{card.sources.map(s=><p key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.id}</a></p>)}<p className="card-note">{card.note}</p></>}</dialog>

 </main>;
}
