'use client';
import {useEffect,useRef,useState,useMemo} from 'react';
import {Compass,Sun,Moon,Sunrise,Sunset,Settings,MapPin,Globe2,BookOpen,Volume2,VolumeX,Headphones,Eye,Type,Check,LockKeyhole,Sparkles,Stamp,MessageCircle,ShieldCheck,ChevronLeft,ChevronRight,CalendarDays,Users,Ticket,Download,Share2,RotateCcw,Clock3,Footprints,Droplets,Landmark,X,ChevronDown,ExternalLink,ArrowUp,Pause,Play} from 'lucide-react';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Progress} from '@/components/ui/progress';
import {Switch} from '@/components/ui/switch';
import experience from '@/data/experience.json';
import {cities,prayerNames,prayerMeanings,scenarioNames,clockState,simulatedDate,nextOccasion,timesFor} from '@/lib/prayer-clock';
import type {contentPayload,Claim} from '@/lib/content-library';
import type {Decision} from '@/lib/discovery-contract';
import {readConversations} from '@/lib/conversation-log';
import {exportPassport} from '@/lib/passport-image';

type Lang='ar'|'en';type View='now'|'explore'|'journeys'|'passport'|'settings'|'discover'|'chat'|'detail'|'journey'|'experiences'|'booking'|'ticket'|'privacy'|'about'|'impact';
type Content=ReturnType<typeof contentPayload>;
type Prefs={lang:Lang;goals:string[];mode:'demo'|'live';city:string;iqamah:number;onboard:boolean;sound:boolean};
type StampRecord={id:string;at:string;type:'moment'|'journey'|'visit-demo';claimIds:string[]};
type ChatMessage={role:'user'|'assistant';text:string;claims?:{claimId:string;text:string;sources:{id:string;url:string;title:string}[]}[];draft?:boolean;error?:boolean};
type RecordRow={at:string;type:string;input?:string;result:unknown};
const defaults:Prefs={lang:'ar',goals:['visit'],mode:'demo',city:'riyadh',iqamah:15,onboard:false,sound:false};
const DEMO_SCENARIO='lahza-demo-scenario';
const PREFS='lahza-prefs-v060',STAMPS='lahza-passport-v1',CARD='lahza-card-v1',LOG='lahza-impact-v060',PROGRESS='lahza-learning-v1';
const passed=(s:string)=>['approved','approved_with_edits'].includes(s);
const Icon=({name,size=24}:{name:string;size?:number})=>{const C=({audio:Volume2,people:Users,sun:Sun,water:Droplets,book:BookOpen,place:Landmark,compass:Compass,chat:MessageCircle} as Record<string,typeof Compass>)[name]||Compass;return <C size={size} aria-hidden/>;};
function safeRead<T,>(key:string,fallback:T):T{try{return JSON.parse(localStorage.getItem(key)||'null')??fallback;}catch{return fallback;}}
function download(value:unknown,name:string){const u=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
const serviceUnavailable={ar:'الخدمة غير متاحة الآن. يمكنك إعادة المحاولة بعد قليل.',en:'The service is unavailable right now. Please try again shortly.'};
const reviewLabel={ar:'مسودة بانتظار المراجعة',en:'Draft awaiting review'};
export default function LahzaApp({qa,initialView='now'}:{qa?:{lang:Lang;screen:string};initialView?:View}={}){
 const [prefs,setPrefs]=useState<Prefs>(defaults),[ready,setReady]=useState(false),[onboarding,setOnboarding]=useState(0),[view,setView]=useState<View>(initialView),[review,setReview]=useState(false);
 const [content,setContent]=useState<Content|null>(null),[contentError,setContentError]=useState(false),[contentLoading,setContentLoading]=useState(true),[reload,setReload]=useState(0);
 const [scenario,setScenario]=useState('before'),[wallTime,setWallTime]=useState(()=>Date.now()),[demoStart,setDemoStart]=useState(()=>Date.now());
 const [passportImage,setPassportImage]=useState<{url:string;file:File}|null>(null);
 const [stamps,setStamps]=useState<StampRecord[]>([]),[page,setPage]=useState(0),[celebrate,setCelebrate]=useState(''),[toast,setToast]=useState('');
 const [moment,setMoment]=useState('adhan'),[branch,setBranch]=useState(''),[source,setSource]=useState<string|null>(null),[adhanOpen,setAdhanOpen]=useState(false),[phraseIndex,setPhraseIndex]=useState(0),[playing,setPlaying]=useState(false),[audioSeconds,setAudioSeconds]=useState(0),[audioDuration,setAudioDuration]=useState(0),[timings,setTimings]=useState<{phraseId:string;start:number;end:number}[]>([]);
 const [cardOpen,setCardOpen]=useState(false),[card,setCard]=useState({observation:'',question:'',explanations:[] as string[],sources:[] as string[]});
 const [modality,setModality]=useState(''),[description,setDescription]=useState(''),[token,setToken]=useState(''),[decision,setDecision]=useState<Decision|null>(null),[asked,setAsked]=useState(0),[initial,setInitial]=useState('');
 const [busy,setBusy]=useState(false),[requestError,setRequestError]=useState(''),[messages,setMessages]=useState<ChatMessage[]>([]),[question,setQuestion]=useState(''),[chatNext,setChatNext]=useState<{id:string;ar:string;en:string}[]>([]);
 const [rows,setRows]=useState<RecordRow[]>([]),[journeyStep,setJourneyStep]=useState(0),[answer,setAnswer]=useState(''),[quizCorrect,setQuizCorrect]=useState(false),[matchIndex,setMatchIndex]=useState(0),[feedback,setFeedback]=useState('');
 const [experienceId,setExperienceId]=useState('mosque'),[bookingStep,setBookingStep]=useState(0),[date,setDate]=useState(''),[slot,setSlot]=useState('10:00'),[people,setPeople]=useState(1),[bookingLang,setBookingLang]=useState<Lang>('en'),[ticket,setTicket]=useState<Record<string,unknown>|null>(null),[locationStatus,setLocationStatus]=useState(''),[citySearch,setCitySearch]=useState('');
 const pending=useRef(false),lastRequest=useRef<(()=>void)|null>(null),heading=useRef<HTMLHeadingElement>(null),audioRef=useRef<HTMLAudioElement|null>(null),autoOpened=useRef('');
 const ar=prefs.lang==='ar',t=(a:string,e:string)=>ar?a:e,txt=(x:{ar:string;en:string})=>x[prefs.lang];const city=cities.find(c=>c.id===prefs.city)||cities[0];
 const virtualDate=useMemo(()=>prefs.mode==='demo'?simulatedDate(scenario,city,prefs.iqamah):new Date(wallTime),[prefs.mode,prefs.iqamah,scenario,city,wallTime,demoStart]);
 const clock=useMemo(()=>clockState(virtualDate,city,prefs.iqamah),[virtualDate,city,prefs.iqamah]);
 const occasion=useMemo(()=>nextOccasion(virtualDate,city),[virtualDate.toDateString(),city]);
 const ftime=(d:Date)=>new Intl.DateTimeFormat(ar?'ar-SA-u-nu-latn':'en-GB',{hour:'2-digit',minute:'2-digit',hour12:false,timeZone:city.zone}).format(d);
 const save=(key:string,value:unknown)=>{try{localStorage.setItem(key,JSON.stringify(value));return true;}catch{setToast(t('تعذّر الحفظ على هذا الجهاز. جرّب إتاحة التخزين في المتصفح.','Could not save on this device. Check browser storage.'));return false;}};
 const patch=(p:Partial<Prefs>)=>setPrefs(old=>({...old,...p}));
 function haptic(){if(typeof navigator!=='undefined'&&'vibrate'in navigator)navigator.vibrate(8);}
 function go(v:View){haptic();setView(v);setRequestError('');setFeedback('');window.scrollTo({top:0,behavior:'instant'});history.replaceState(null,'',v==='impact'?'/judge':'/?view='+v);}
 function log(type:string,input:string,result:unknown){setRows(old=>{const all=[...old,{at:new Date().toISOString(),type,input,result}].slice(-200);save(LOG,all);return all;});}
 useEffect(()=>{if(qa&&process.env.NODE_ENV==='development'){const [section,sub]=qa.screen.split(':');setPrefs({...defaults,lang:qa.lang,onboard:section!=='welcome'});setOnboarding(Number(sub)||0);setView((section==='welcome'?'now':section==='now'||section==='time'||section==='adhan'?'now':section==='review'?'explore':section==='journey'?'journey':section==='source'?'detail':section==='card'?'chat':section==='discover-error'?'discover':section==='chat-refusal'?'chat':section==='ticket'?'ticket':section) as View);setReview(section==='review');if(section==='now')setScenario(sub||'before');if(section==='adhan')setAdhanOpen(true);if(section==='time'){setView('detail');setMoment('dhuhr');setBranch('time');}if(section==='detail'||section==='source')setBranch('adhan-what');if(section==='source')setSource('BUK-631');if(section==='journey')setJourneyStep(Number(sub)||0);if(section==='passport')setPage(Number(sub)||0);if(section==='booking')setBookingStep(Number(sub)||0);setDate('2026-10-06');if(section==='ticket')setTicket({id:'DEMO-VISUAL',date:'2026-10-06',slot:'10:00',people:2,language:qa.lang,demo:true});if(section==='card')setCardOpen(true);if(section==='discover'&&sub)setModality(sub);if(section==='discover-error'){setModality('sound');setRequestError(serviceUnavailable[qa.lang]);}if(section==='chat-refusal')setMessages([{role:'user',text:qa.lang==='ar'?'ما الأذان؟':'What is the adhan?'},{role:'assistant',text:qa.lang==='ar'?'لا أملك نصًا مطابَقًا على مصدره يجيب عن هذا السؤال':'I do not have source-verified text that answers this question.'}]);setReady(true);return;}const saved=safeRead<Partial<Prefs>>(PREFS,{});const selectedScenario=safeRead<string>(DEMO_SCENARIO,'before');if(scenarioNames.some(x=>x.id===selectedScenario))setScenario(selectedScenario);setPrefs({...defaults,...saved,lang:saved.lang==='en'?'en':'ar',goals:Array.isArray(saved.goals)&&saved.goals.length?saved.goals.filter(x=>experience.goals.some(g=>g.id===x)):['visit'],city:cities.some(c=>c.id===saved.city)?saved.city!:'riyadh',iqamah:Number.isFinite(saved.iqamah)?Math.max(5,Math.min(60,saved.iqamah!)):15});setStamps(safeRead(STAMPS,[]));setCard(safeRead(CARD,{observation:'',question:'',explanations:[],sources:[]}));setRows(safeRead(LOG,[]));const v=new URLSearchParams(location.search).get('view');if(location.pathname==='/judge')setView('impact');if(location.pathname==='/about')setView('about');if(['now','explore','journeys','passport','settings','discover','chat','experiences','privacy','about','impact'].includes(v||''))setView(v as View);setReady(true);},[]);
 useEffect(()=>{if(ready){if(!qa)save(PREFS,prefs);document.documentElement.lang=prefs.lang;document.documentElement.dir=ar?'rtl':'ltr';document.title=t('لَحْظَة | افهم ما حولك','LAHZA | Understand your moment');}},[prefs,ready]);
 useEffect(()=>{if(qa)return;setDecision(null);setToken('');setAsked(0);setMessages([]);setChatNext([]);setRequestError('');},[prefs.lang]);
 useEffect(()=>{const timer=setInterval(()=>setWallTime(Date.now()),1000);return ()=>clearInterval(timer);},[]);
 useEffect(()=>{if(!ready)return;let active=true;setContentLoading(true);setContentError(false);setContent(null);fetch('/api/content'+(review?'?review=1':''),{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(d=>{if(active){setContent(d as Content);setContentLoading(false);}}).catch(()=>{if(active){setContentError(true);setContentLoading(false);}});return ()=>{active=false;};},[ready,review,reload]);
 useEffect(()=>{if(view==='now'&&prefs.onboard&&clock.state==='adhan'){const key=prefs.mode+scenario+virtualDate.toDateString()+clock.previous?.key;if(autoOpened.current!==key){autoOpened.current=key;setAdhanOpen(true);}}},[clock.state,view,prefs.onboard,prefs.mode,scenario]);
 useEffect(()=>{if(toast){const timer=setTimeout(()=>setToast(''),4500);return ()=>clearTimeout(timer);}},[toast]);
 useEffect(()=>{if(celebrate){const timer=setTimeout(()=>setCelebrate(''),1800);return ()=>clearTimeout(timer);}},[celebrate]);
 useEffect(()=>{if(ready)heading.current?.focus({preventScroll:true});},[view]);
 const getClaims=(id:string,b?:string)=>(content?.claims||[]).filter(c=>c.momentId===id&&(!b||c.branchId===b));
 const getMoment=(id:string)=>content?.moments.find(m=>m.id===id);
 const momentName=(id:string)=>{const m=getMoment(id);return m?(ar?m.name_ar:m.name_en):id;};
 const branches=(id?:string)=>(content?.moments||[]).filter(m=>!id||m.id===id).flatMap(m=>m.branches.filter(b=>b.claimIds.length).map(b=>({id:b.id,ar:b.title_ar,en:b.title_en}))).slice(0,3);
 const currentMoment=clock.state==='friday'?'khutbah':clock.state==='prayer'?'congregational-prayer':clock.state==='between'?'iqamah':'adhan';
 const currentClaims=getClaims(currentMoment);
 const purposeRows=experience.purposeLines as {goal:string;states:string[];claimId:string}[];
 const purposeClaim=(goal:string)=>purposeRows.filter(r=>r.goal===goal&&r.states.includes(clock.state)).map(r=>content?.claims.find(c=>c.claimId===r.claimId&&passed(c.reviewStatus))).find(Boolean);
 const purpose=purposeClaim(prefs.goals[0])||purposeClaim('general');

 function openMoment(id:string,b=''){setMoment(id);setBranch(b);go('detail');}
 function earn(id:string,type:StampRecord['type'],claimIds:string[]){if(type!=='visit-demo'&&(review||claimIds.length===0||claimIds.some(id=>!content?.claims.some(c=>c.claimId===id&&passed(c.reviewStatus)))))return;if(stamps.some(s=>s.id===id))return;const all=[...stamps,{id,type,claimIds,at:new Date().toISOString()}];if(save(STAMPS,all)){setStamps(all);setCelebrate(id);haptic();if(prefs.sound){try{const A=window.AudioContext;const ctx=new A(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.connect(gain);gain.connect(ctx.destination);osc.frequency.value=620;gain.gain.setValueAtTime(.03,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.13);osc.start();osc.stop(ctx.currentTime+.14);osc.onended=()=>ctx.close();}catch{}}}}
 function prepareCard(observation=initial||description,questionText=question){const c={observation,question:questionText,explanations:messages.flatMap(m=>m.claims?.map(c=>c.text)||[]),sources:[...new Set(messages.flatMap(m=>m.claims?.flatMap(c=>c.sources.map(s=>s.id))||[]))]};setCard(c);save(CARD,c);setCardOpen(true);}
 async function discover(action='start',text=description){if(pending.current||!text.trim()&&['start','reply'].includes(action))return;pending.current=true;setBusy(true);setRequestError('');lastRequest.current=()=>discover(action,text);if(action==='start'){setInitial(text);setDecision(null);setToken('');setAsked(0);}try{const r=await fetch('/api/moments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,text,language:prefs.lang,token,modality})});const d=await r.json() as any;log('discovery',text,{action,...d,token:undefined});if(!r.ok)throw Error();setToken(d.token||'');setAsked(d.askedCount||0);setDescription('');if(d.kind==='explanation'){const cs=d.result?.claims||[];setMessages([{role:'assistant',text:'',claims:cs.map((c:any)=>({...c,sources:[{id:c.sourceId,url:c.url,title:(()=>{const src=content?.sources.find(s=>s.id===c.sourceId);return src?(ar?src.title_ar:src.title_en):c.sourceId;})()}]}))}]);go('chat');}else setDecision(d.decision);}catch{setChatNext([]);setRequestError(serviceUnavailable[prefs.lang]);}finally{pending.current=false;setBusy(false);}}
 async function chat(q:string,b?:string){if(pending.current||!q.trim())return;pending.current=true;setBusy(true);setRequestError('');setQuestion('');go('chat');setMessages(old=>[...old,{role:'user',text:q}]);lastRequest.current=()=>chat(q,b);try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q,language:prefs.lang,branchId:b})});const d=await r.json() as any;log('chat',q,d);if(!r.ok)throw Error();setMessages(old=>[...old,{role:'assistant',text:d.message||'',claims:d.claims}]);setChatNext(d.next||[]);}catch{setChatNext([]);setRequestError(serviceUnavailable[prefs.lang]);}finally{pending.current=false;setBusy(false);}}
 const startChat=(q:string,b?:string)=>{setMessages([]);setChatNext([]);chat(q,b);};
 const onReview=(value:boolean)=>{setReview(value);setMessages([]);setJourneyStep(0);setAnswer('');setQuizCorrect(false);setMatchIndex(0);setToast(value?t('أنت الآن في وضع المراجع. لن تُمنح أختام تعلّم للمسودات.','Review mode is on. Drafts do not earn learning stamps.'):t('عدت إلى وضع الزائر.','Visitor mode is on.'));};
 const journey=experience.journey,journeyClaims=journey.claimIds.map(id=>content?.claims.find(c=>c.claimId===id)).filter(Boolean) as Claim[];
 const journeyReady=journeyClaims.length===journey.claimIds.length&&journeyClaims.every(c=>passed(c.reviewStatus))&&journeyClaims.some(c=>c.claimId===journey.question.claimId&&c.momentId===journey.question.answer)&&journey.matching.pairs.every(p=>journeyClaims.some(c=>c.claimId===p.claimId&&c.momentId===p.moment));
 const canJourney=journeyReady||(review&&journeyClaims.length===journey.claimIds.length);
 const startJourney=()=>{setJourneyStep(review?0:Math.min(safeRead<number>(PROGRESS,0),5));setQuizCorrect(false);setAnswer('');setMatchIndex(0);setFeedback('');go('journey');};
 const advanceJourney=()=>{const next=Math.min(journeyStep+1,5);setJourneyStep(next);setFeedback('');if(!review)save(PROGRESS,next);};
 const selectedExperience=experience.experiences.find(x=>x.id===experienceId)||experience.experiences[0];
 const demoNotice=t('نموذج تجريبي. الحجز غير مفعّل بعد، والبيانات المعروضة نموذجية.','Demo only. Booking is not active. All displayed details are sample data.');
 const upcomingDates=Array.from({length:7},(_,i)=>{const d=new Date(wallTime+(i+1)*86400000);return new Intl.DateTimeFormat('en-CA',{timeZone:city.zone,year:'numeric',month:'2-digit',day:'2-digit'}).format(d);});
 // Geolocation is requested only by the nearest-place button; no coordinates are persisted or sent.
 function askLocation(){setLocationStatus(t('جارٍ طلب إذن الموقع…','Requesting location permission…'));if(!navigator.geolocation){setLocationStatus(t('الموقع غير متاح. ابحث بالمدينة.','Location is unavailable. Search by city.'));return;}navigator.geolocation.getCurrentPosition(p=>{const near=[...cities].sort((a,b)=>(a.lat-p.coords.latitude)**2+(a.lng-p.coords.longitude)**2-((b.lat-p.coords.latitude)**2+(b.lng-p.coords.longitude)**2))[0];setCitySearch(near[prefs.lang]);setLocationStatus(t('أقرب مدينة في الدليل التجريبي: '+near.ar+'. لم يُحفظ موقعك.','Nearest city in the sample directory: '+near.en+'. Your location was not saved.'));},()=>setLocationStatus(t('يمكنك المتابعة بالبحث باسم المدينة.','You can continue by searching for your city.')),{enableHighAccuracy:false,maximumAge:0,timeout:10000});}
 const Empty=({title,body,action}:{title:string;body?:string;action?:React.ReactNode})=><div className="empty-state"><div className="empty-icon"><BookOpen size={32}/></div><h3>{title}</h3>{body&&<p>{body}</p>}{action}</div>;
 const Draft=()=>review?<span className="badge draft"><ShieldCheck size={14}/>{reviewLabel[prefs.lang]}</span>:null;
 const ContentState=()=>contentError?<Empty title={t('تعذّر تحميل المحتوى','Couldn’t load the content')} action={<button className="primary" onClick={()=>setReload(x=>x+1)}>{t('إعادة المحاولة','Try again')}</button>}/>:contentLoading?<div className="skeletons" role="status" aria-label={t('جارٍ التحميل','Loading')}><div/><div/><div/></div>:null;
 const Verified=()=> <span className="badge verified"><ShieldCheck size={14}/>{t('مطابَق على مصدره','Verified against its source')}</span>;
 const SourceLinks=({ids}:{ids:string[]})=><div className="source-links">{ids.map(id=>{const src=content?.sources.find(x=>x.id===id);return src?<a key={id} className="source-chip" href={src.url} target="_blank" rel="noopener noreferrer"><BookOpen size={14}/><span>{ar?src.title_ar:src.title_en}</span><ExternalLink size={12}/></a>:null;})}</div>;
 const ClaimView=({claim}:{claim:Claim})=><div className="claim" data-claim-id={claim.claimId}>{passed(claim.reviewStatus)?<Verified/>:<span className="badge draft">{reviewLabel[prefs.lang]}</span>}<p>{ar?claim.text_ar:claim.text_en}</p><SourceLinks ids={claim.sourceIds}/></div>;
 const QuestionButtons=({items=branches(currentMoment)}:{items?:{id:string;ar:string;en:string}[]})=><div className="question-list">{items.map(q=><button key={q.id} className="question-button" onClick={()=>startChat(txt(q),q.id)}><MessageCircle size={19}/><span>{txt(q)}</span><span className="tiny-dot"/></button>)}</div>;
 const ButtonBack=({to='now' as View}:{to?:View})=><button className="icon-btn" onClick={()=>go(to)} aria-label={t('رجوع','Back')}>{ar?<ChevronRight/>:<ChevronLeft/>}</button>;
 const titleMap:Record<View,string>={now:t('لحظتك، الآن.','Your moment. Right now.'),explore:t('اتبع فضولك.','Follow your curiosity.'),journeys:t('فهمٌ يبقى معك.','Understanding that stays.'),passport:t('جواز لحظاتك.','Your moment passport.'),settings:t('على طريقتك.','Make it yours.'),discover:t('ما الذي لفت انتباهك؟','What caught your attention?'),chat:t('سؤال يفتح نافذة.','A question opens a window.'),detail:branch==='time'?(ar?prayerNames[moment as keyof typeof prayerNames]?.ar:(prayerNames[moment as keyof typeof prayerNames]?.en+', the '+prayerMeanings[moment as keyof typeof prayerMeanings]+' prayer')):momentName(moment),journey:txt(journey),experiences:t('من الفهم إلى اللقاء.','From understanding to meeting.'),booking:txt(selectedExperience),ticket:t('تذكرتك التجريبية','Your demo ticket'),privacy:t('خصوصيتك أولًا.','Your privacy comes first.'),about:t('عن لَحْظَة','About LAHZA'),impact:t('أثر السؤال','Question impact')};
 const navItems=[{id:'now',ar:'الآن',en:'Now',I:Sun},{id:'explore',ar:'استكشف',en:'Explore',I:Compass},{id:'journeys',ar:'الرحلات',en:'Journeys',I:Footprints},{id:'passport',ar:'الجواز',en:'Passport',I:Stamp}];
 const mainNav=['now','explore','journeys','passport'].includes(view);
 const visiblePhrases=getClaims('adhan','adhan-lines').filter(c=>passed(c.reviewStatus)&&Number.isInteger(c.order)&&Number.isInteger(c.repeat)&&c.repeat!>0).sort((a,b)=>a.order!-b.order!).flatMap(c=>Array.from({length:c.repeat!},(_,i)=>({id:c.claimId+'-'+i,claim:c,repetition:i+1,total:c.repeat!})));
 function selectPhrase(i:number){setPhraseIndex(Math.max(0,Math.min(i,visiblePhrases.length-1)));}



 return <div className="lahza-app" dir={ar?'rtl':'ltr'} lang={prefs.lang} onClick={()=>haptic()}>
 <header className="app-header"><button className="brand" onClick={()=>go('now')} aria-label={t('لحظة، الرئيسية','LAHZA home')}><span className="brand-mark"><Compass size={25}/></span><span>لَحْظَة<small>LAHZA</small></span></button><div className="header-actions">{(prefs.onboard||view==='impact')&&<button className="language-toggle" disabled={busy} onClick={()=>patch({lang:ar?'en':'ar'})}><Globe2 size={17}/>{ar?'EN':'عربي'}</button>}<button className={'icon-btn '+(view==='settings'?'selected':'')} disabled={busy} onClick={()=>go('settings')} aria-label={t('الإعدادات','Settings')}><Settings size={21}/></button></div></header>
 {!prefs.onboard&&!['settings','impact'].includes(view)?<main className={"onboarding onboarding-step-"+onboarding}>
 <div className="step-top"><span>{t('خطوة','Step')} {onboarding+1} / 3</span><button className="text-button" onClick={()=>{patch({onboard:true});setDemoStart(Date.now());go('now');}}>{t('تخطّ','Skip')}</button></div><Progress value={(onboarding+1)/3*100} aria-label={t('تقدم البداية','Welcome progress')}/>
 <div className="welcome-symbol"><Icon name={onboarding===0?'compass':onboarding===1?'place':'sun'} size={48}/><span className="orbit-dot"/></div>
 <div className="eyebrow">{onboarding===0?'لَحْظَة · LAHZA':t('رحلتك تبدأ هنا','Your journey starts here')}</div>
 <h1>{onboarding===0?t('اقترب من اللحظة.','Step into the moment.'):onboarding===1?t('لماذا تستخدم لحظة؟','What brings you to LAHZA?'):t('كيف نبدأ؟','How shall we begin?')}</h1>
 <p className="lead">{onboarding===0?t('افهم ما حولك، بلغتك.','Understand what’s around you, in your language.'):onboarding===1?t('اختر ما يهمك. أول اختيار سيكون غايتك الأساسية.','Choose what interests you. Your first choice is your main goal.'):t('اختر وقتًا للتجربة. يمكنك تغييره لاحقًا.','Choose a time mode. You can change it later.')}</p>
 {onboarding===0?<div className="option-stack"><button className={'option language-option '+(ar?'selected':'')} onClick={()=>patch({lang:'ar'})}><span className="language-glyph">ع</span><span><strong>العربية</strong><small>ابدأ بلغتك</small></span>{ar&&<Check/>}</button><button className={'option language-option '+(!ar?'selected':'')} onClick={()=>patch({lang:'en'})}><span className="language-glyph">Aa</span><span><strong>English</strong><small>Make yourself at home</small></span>{!ar&&<Check/>}</button></div>:onboarding===1?<div className="option-stack">{experience.goals.map(g=><button key={g.id} className={'option goal-option '+(prefs.goals.includes(g.id)?'selected':'')} aria-pressed={prefs.goals.includes(g.id)} onClick={()=>patch({goals:prefs.goals.includes(g.id)?prefs.goals.filter(x=>x!==g.id):[...prefs.goals,g.id]})}><span className="choice-check">{prefs.goals.includes(g.id)&&<Check size={16}/>}</span><span>{txt(g)}{prefs.goals[0]===g.id&&<small>{t('غايتك الأساسية','Your main goal')}</small>}</span></button>)}</div>:<div className="option-stack">{(['demo','live'] as const).map(mode=><button key={mode} className={'option mode-option '+(prefs.mode===mode?'selected':'')} onClick={()=>patch({mode})}><span className="tile-icon">{mode==='demo'?<Sparkles/>:<Clock3/>}</span><span><strong>{mode==='demo'?t('عرض توضيحي','Demo mode'):t('الوقت الفعلي','Live time')}</strong>{mode==='demo'&&<small className="gold-text">{t('موصى به','Recommended')}</small>}<small>{mode==='demo'?t('اكتشف خصائص التطبيق بأوقات معدّة للعرض.','Explore the app with times prepared for a demo.'):t('شاهد ما يحدث الآن في مدينتك.','See the time in your city right now.')}</small></span>{prefs.mode===mode&&<Check size={20}/>}</button>)}<p className="fine-print">{t('يمكنك تغيير الوضع من الإعدادات في أي وقت.','You can change modes in Settings at any time.')}</p></div>}
 <button className="primary" disabled={onboarding===1&&!prefs.goals.length||!ready} onClick={()=>onboarding<2?setOnboarding(x=>x+1):(patch({onboard:true}),setDemoStart(Date.now()),go('now'))}>{onboarding===2?t('ابدأ لحظتك','Start your moment'):t('متابعة','Continue')}</button>{onboarding>0&&<button className="text-button back-text" onClick={()=>setOnboarding(x=>x-1)}>{t('رجوع','Back')}</button>}
 </main>:<>
 {review&&<div className="review-bar"><ShieldCheck size={17}/><span>{t('وضع المراجع: المسودات ظاهرة في سياقها','Review mode: drafts are visible in context')}</span></div>}
 <main className={'page-content view-'+view}>
 <div className="page-heading">{!mainNav&&<ButtonBack to={view==='booking'?'experiences':view==='detail'?'explore':view==='journey'?'journeys':view==='ticket'?'experiences':['about','privacy','impact'].includes(view)?'settings':'now'}/>}<div><div className="eyebrow">{view==='now'?t('افهم ما حولك','UNDERSTAND YOUR SURROUNDINGS'):view==='passport'?t('رحلةٌ تخصّك','A JOURNEY OF YOUR OWN'):'لَحْظَة · LAHZA'}</div><h1 ref={heading} tabIndex={-1}>{titleMap[view]}</h1></div></div>
 {view==='now'&&<>
 <div className="time-row"><button className="city-button" onClick={()=>go('settings')}><MapPin size={16}/>{city[prefs.lang]}<ChevronDown size={14}/></button><div className="clock"><time>{ftime(virtualDate)}</time><span className={'badge '+(prefs.mode==='demo'?'demo':'live')}>{prefs.mode==='demo'?t('عرض توضيحي','Demo'):t('وقت فعلي','Live time')}</span></div></div>
 {prefs.mode==='demo'&&<div className="scenario-strip" aria-label={t('مشاهد العرض التوضيحي','Demo scenarios')}>{scenarioNames.map(s=><button key={s.id} className={scenario===s.id?'active':''} aria-pressed={scenario===s.id} onClick={()=>{setScenario(s.id);save(DEMO_SCENARIO,s.id);setDemoStart(Date.now());setWallTime(Date.now());}}>{txt(s)}</button>)}</div>}
 <section className="now-hero"><div className="hero-top"><span className="badge hero-badge"><span className="pulse-dot"/>{prefs.mode==='demo'?t('لحظة من العرض','A DEMO MOMENT'):t('وفق الوقت التقريبي','ESTIMATED TIMING')}</span></div><div className="hero-content"><div className="hero-heading"><div className="hero-copy"><h2>{clock.state==='before'?t('اقترب أذان '+clock.next.ar,clock.next.en+' is near'):clock.state==='adhan'?t('الأذان الآن','Adhan: the call to prayer'):clock.state==='between'?t('بين الأذان والإقامة','Before iqamah'):clock.state==='prayer'?t('وقت الصلاة','Prayer time'):clock.state==='friday'?t('ظهر الجمعة','Friday noon'):t('الصلاة القادمة: '+clock.next.ar,'Next: '+clock.next.en)}</h2>{!ar&&['before','next','between'].includes(clock.state)&&<p className="hero-term">{clock.state==='between'?'The call as prayer begins':'The '+prayerMeanings[clock.next.key]+' prayer'}</p>}{['before','next'].includes(clock.state)?<div className="countdown" dir="ltr">{String(Math.floor(clock.remaining/3600)).padStart(2,'0')}<span>:</span>{String(Math.floor(clock.remaining%3600/60)).padStart(2,'0')}<span>:</span>{String(clock.remaining%60).padStart(2,'0')}</div>:null}</div><div className="hero-illustration"><img src="/art/neutral-mosque-medallion.png" alt=""/></div></div>
 {currentClaims[0]?<div className="hero-caption"><ClaimView claim={currentClaims[0]}/></div>:<p className="hero-caption">{t('لحظة تستحق أن تتوقف عندها.','A moment to pause and explore.')}</p>}
 <button className="primary gold" onClick={()=>clock.state==='adhan'?setAdhanOpen(true):openMoment(currentMoment)}>{clock.state==='adhan'?t('افهم الأذان الذي تسمعه','Understand the call to prayer (adhan)'):t('اعرف أكثر','Explore this moment')}</button></div></section>
 <section className="panel day-panel"><div className="section-heading"><h2>{t('خط يومك','Your day at a glance')}</h2><span>{t('تقريبي','Approximate')}</span></div><div className="prayer-timeline">{clock.times.map((p,i)=>{const current=clock.previous?.key===p.key;const I=[Sunrise,Sun,Sun,Sunset,Moon][i];return <button key={p.key} className={(current?'current ':'')+(p.date<virtualDate?'elapsed':'')} onClick={()=>{setMoment(p.key);setBranch('time');go('detail');}} aria-label={(ar?p.ar:p.en+', the '+prayerMeanings[p.key]+' prayer')+' '+ftime(p.date)+(current?t('، هنا الآن',', current interval'):'')}><span className="timeline-icon"><I size={20}/></span><strong>{ar?p.ar:prayerMeanings[p.key][0].toUpperCase()+prayerMeanings[p.key].slice(1)}</strong><time>{ftime(p.date)}</time>{current&&<span className="here-dot"/>}</button>;})}</div><p className="fine-print">{t('حساب على جهازك بطريقة أم القرى.','Calculated on your device using Umm al-Qura.')} <a href="https://www.ummulqura.org.sa/" target="_blank" rel="noreferrer">{t('المصدر الرسمي','Official source')}</a></p>{prefs.mode==='demo'&&<p className="fine-print">{t('هذا الخط تابع لساعة العرض التوضيحي.','This timeline follows the demo clock.')}</p>}</section>
 {purpose&&<section className="panel"><h2>{t('ماذا يعني هذا لي؟','What does this mean for me?')}</h2><ClaimView claim={purpose}/></section>}
 {branches(currentMoment).length>0&&<section><div className="section-heading"><h2>{t('ربما تتساءل…','You might be wondering…')}</h2></div><QuestionButtons/></section>}
 {occasion&&<button className="occasion-card" onClick={()=>{setSource('calendar');}}><span className="occasion-icon"><Moon size={26}/></span><span><small>{t('قريبًا','ON THE HORIZON')}</small><strong>{occasion[prefs.lang]}</strong><small>{t('تقريبي وفق تقويم أم القرى','Approximate, Umm al-Qura calendar')}</small></span><span className="days"><b>{occasion.days}</b><small>{t('يومًا','days')}</small></span></button>}
 <button className="discovery-entry" onClick={()=>{setModality('');setDecision(null);setDescription('');go('discover');}}><span className="tile-icon"><Compass/></span><span><strong>{t('رأيت أو سمعت شيئًا آخر؟','Noticed something else?')}</strong><small>{t('ابدأ بما لفت انتباهك.','Start with what caught your attention.')}</small></span></button>
 
 </>}
 {view==='explore'&&<><button className="question-button" onClick={()=>go('chat')}><MessageCircle size={20}/>{t('لدي سؤال','I have a question')}</button><p className="lead">{t('مواقف صغيرة. نوافذ لفهم أكبر.','Small encounters. New ways to understand.')}</p><ContentState/>{!contentLoading&&!contentError&&<>{experience.explore.some(x=>getClaims(x.moment,x.branch).length)?<div className="explore-grid">{[...experience.explore].sort((a,b)=>Number(b.goals.includes(prefs.goals[0]))-Number(a.goals.includes(prefs.goals[0]))).filter(x=>getClaims(x.moment,x.branch).length).map((x,i)=><button className={'explore-card tone-'+i%3} key={x.id} onClick={()=>openMoment(x.moment,x.branch)}><span className="explore-icon"><Icon name={x.icon} size={32}/></span><small>{momentName(x.moment)}</small><strong>{txt(x)}</strong>{review&&<span className="draft-label">{reviewLabel[prefs.lang]}</span>}</button>)}</div>:<Empty title={t('نعدّ لك نوافذ موثوقة.','Thoughtful answers are on the way.')} body={t('ستظهر المواقف هنا حين تتوفر نصوص مطابَقة على مصادرها. يمكنك الآن وصف لحظة لفتت انتباهك.','Scenes will appear here when source-verified text is available. You can describe a moment that caught your attention.')} action={<button className="primary" onClick={()=>go('discover')}>{t('اكتشف لحظة','Discover a moment')}</button>}/>}</>}
 <button className="experience-entry" onClick={()=>go('experiences')}><span className="tile-icon"><MapPin/></span><span><strong>{t('استكشف تجارب اللقاء','Explore experiences')}</strong><small>{t('زيارة، جولة، حوار · نموذج تجريبي','Visit, walk, conversation · Demo')}</small></span><span className="badge demo">{t('تجريبي','Demo')}</span></button></>}
 {view==='detail'&&<>{branch==='time'?<section className="panel"><div className="detail-emblem"><Clock3 size={42}/></div><h2>{ar?prayerNames[moment as keyof typeof prayerNames]?.ar:prayerNames[moment as keyof typeof prayerNames]?.en+', the '+prayerMeanings[moment as keyof typeof prayerMeanings]+' prayer'}</h2><div className="large-time">{ftime(clock.times.find(x=>x.key===moment)?.date||virtualDate)}</div><span className="badge demo">{prefs.mode==='demo'?t('وقت محاكاة','Simulated time'):t('وقت تقريبي','Approximate time')}</span><p>{t('المواقيت محسوبة على الجهاز بطريقة أم القرى للمدينة المختارة. تحقّق من المصدر الرسمي.','Times are calculated on your device using Umm al-Qura for your selected city. Check the official source.')}</p><a className="outlined link-button" href="https://www.ummulqura.org.sa/" target="_blank" rel="noreferrer">{t('تقويم أم القرى','Umm al-Qura calendar')}</a></section>:<><div className="detail-emblem"><Icon name={moment==='wudu'?'water':moment==='khutbah'?'book':moment==='congregational-prayer'?'people':'audio'} size={40}/></div><ContentState/>{!contentLoading&&!contentError&&(getClaims(moment,branch).length?<><div className="claim-stack">{getClaims(moment,branch).map(c=><ClaimView key={c.claimId} claim={c}/>)}</div>{!review&&<button className="primary" onClick={()=>{earn('moment-'+moment,'moment',getClaims(moment,branch).map(c=>c.claimId));go('passport');}}>{stamps.some(s=>s.id==='moment-'+moment)?t('شاهد ختمك','See your stamp'):t('فهمت هذه اللحظة','I understand this moment')}</button>}<h2 className="section-title">{t('واصل فضولك','Keep exploring')}</h2><QuestionButtons items={branches(moment)}/></>:<Empty title={t('لكل فهم مصدر.','Understanding needs a source.')} body={t('لا يتوفر نص مطابَق على مصدره لهذه اللحظة. احتفظ بسؤالك في بطاقة للحوار.','No source-verified text is available for this moment. Keep your question in a conversation card.')} action={<button className="primary" onClick={()=>prepareCard(momentName(moment),'')}>{t('جهّز بطاقة الحوار','Create a conversation card')}</button>}/>)}{moment==='adhan'&&<button className="outlined" onClick={()=>setAdhanOpen(true)}><BookOpen size={20}/>{t('نافذة الأذان','Read the call to prayer (adhan)')}</button>}</>}</>}
 {view==='discover'&&<><p className="lead">{t('لا تحتاج إلى معرفة اسمه. ابدأ بما لاحظت.','You don’t need its name. Start with what you noticed.')}</p><Progress value={decision?.decision==='stop'?100:asked/2*100} aria-label={t('تقدم الاكتشاف','Discovery progress')}/>{initial&&decision&&<details className="observation"><summary>{t('ما وصفته','What you noticed')}</summary><p dir="auto">{initial}</p></details>}
 {!decision&&!modality&&<div className="modality-list">{[{id:'sound',ar:'سمعت صوتًا',en:'I heard something',I:Headphones},{id:'visual',ar:'رأيت مشهدًا',en:'I saw something',I:Eye},{id:'text',ar:'قرأت كتابة',en:'I noticed some writing',I:Type}].map(x=><button className="option" key={x.id} onClick={()=>setModality(x.id)}><span className="tile-icon"><x.I/></span><strong>{txt(x)}</strong></button>)}</div>}
 {decision&&!requestError&&<section className="panel decision-panel" aria-live="polite"><span className="badge">{t('أسئلة الاستيضاح','Clarifying questions')} {asked}/2</span><h2>{decision.decision==='ask'?t('تفصيل صغير يساعدنا','One detail can help'):decision.decision==='confirm'?t('هل نقترب مما لاحظت؟','Does this fit what you noticed?'):t('هنا تنتهي معرفتنا الآن.','This is where our knowledge ends for now.')}</h2><p>{decision.message}</p>{decision.why_this_question&&<p className="muted">{decision.why_this_question}</p>}{decision.decision==='confirm'&&<><div className="evidence-list">{decision.evidence.map(e=><blockquote key={e} dir="auto">{e}</blockquote>)}</div><button className="primary" disabled={busy} onClick={()=>discover('accept','')}>{t('أريد فهم هذا الاحتمال','Explore this possibility')}</button><div className="two-buttons"><button className="outlined" disabled={busy} onClick={()=>discover('unsure','')}>{t('لست متأكدًا','I’m not sure')}</button><button className="outlined" disabled={busy} onClick={()=>discover('reject','')}>{t('ليس ما أقصده','Not what I meant')}</button></div><label>{t('تفصيل آخر، إن أردت','Another detail, if you wish')}<textarea value={description} onChange={e=>setDescription(e.target.value)} maxLength={1200}/></label><button className="text-button" disabled={busy||!description.trim()} onClick={()=>discover('reject')}>{t('أضف التفصيل وصحّح الاحتمال','Add detail and revise')}</button></>}{decision.decision==='stop'&&<><button className="primary" onClick={()=>prepareCard()}>{t('احتفظ بسؤالك','Keep your question')}</button><button className="text-button" onClick={()=>{setDecision(null);setModality('');setInitial('');setToken('');setDescription('');setAsked(0);}}>{t('لحظة جديدة','A new moment')}</button></>}</section>}
 {!requestError&&(!decision&&modality||decision?.decision==='ask')&&<form className="panel discovery-form" onSubmit={e=>{e.preventDefault();discover(decision?'reply':'start');}}><label htmlFor="description">{decision?t('أجب بكلماتك','Answer in your own words'):t('صف ما لاحظت','Describe what you noticed')}</label><textarea id="description" rows={4} maxLength={1200} disabled={busy} value={description} onChange={e=>setDescription(e.target.value)} placeholder={modality==='sound'?t('سمعت…','I heard…'):modality==='visual'?t('رأيت…','I saw…'):t('كانت الكتابة تقول…','The writing said…')}/>{!decision&&<div className="example-chips">{(modality==='sound'?[t('سمعت صوتًا بالعربية في مكان عام','I heard a voice in Arabic in a public place'),t('سمعت نداءً قصيرًا من مبنى','I heard a short call from a building')]:modality==='visual'?[t('رأيت أشخاصًا يقفون في صفوف','I saw people standing in rows'),t('رأيت أشخاصًا يغسلون أقدامهم','I saw people washing their feet')]:[t('رأيت كتابة على مبنى ولا أستطيع قراءتها','I noticed writing on a building that I could not read')]).map(s=><button type="button" key={s} onClick={()=>setDescription(s)}>{s}</button>)}</div>}<button className="primary" disabled={busy||!description.trim()}>{busy?t('نتأمل وصفك…','Considering your description…'):t('اكتشف اللحظة','Discover the moment')}</button>{decision&&<button type="button" className="text-button" disabled={busy} onClick={()=>discover('reply',t('لا أعرف','I don’t know'))}>{t('لا أعرف','I don’t know')}</button>}</form>}
 <p className="fine-print"><ShieldCheck size={15}/>{t('يُرسل وصفك إلى خدمة ذكاء اصطناعي لمعالجته.','Your description is sent to an AI service for processing.')}</p></>}
 {view==='chat'&&<><div className="source-assurance"><ShieldCheck size={18}/>{t('كل جملة لها مصدر.','A source for every sentence.')}</div><div className="chat-messages" aria-live="polite">{messages.length===0&&<Empty title={t('بماذا تتساءل؟','What are you wondering about?')} body={t('اكتب سؤالك، وسنبحث في المحتوى المطابَق على مصادره.','Ask a question and we’ll look in the source-verified content.')}/>} {messages.map((m,i)=><div className={'chat-bubble '+m.role} key={i}>{m.role==='assistant'&&<span className="bubble-brand"><Compass size={17}/> LAHZA</span>}{m.text&&<p dir="auto">{m.text}</p>}{m.claims?.map(c=><div className="chat-claim" key={c.claimId}><p>{c.text}</p><Verified/><SourceLinks ids={c.sources.map(s=>s.id)}/></div>)}{m.role==='assistant'&&!m.claims?.length&&<button className="outlined" onClick={()=>prepareCard('',messages[i-1]?.text||question)}>{t('بطاقة الحوار','Conversation card')}</button>}</div>)}{busy&&<div className="chat-bubble assistant typing" role="status" aria-label={t('جارٍ البحث في المصادر','Looking through sources')}><i/><i/><i/></div>}</div>{chatNext.length>0&&!busy&&!requestError&&<QuestionButtons items={chatNext}/>}<form className="chat-compose" onSubmit={e=>{e.preventDefault();chat(question);}}><label className="sr-only" htmlFor="chat-question">{t('سؤالك','Your question')}</label><textarea id="chat-question" value={question} onChange={e=>setQuestion(e.target.value)} rows={2} maxLength={1200} placeholder={t('ما الذي يثير فضولك؟','What are you curious about?')}/><button className="primary send" disabled={busy||!question.trim()} aria-label={t('إرسال السؤال','Send question')}><ArrowUp/></button></form></>}
 {view==='journeys'&&<><p className="lead">{t('خطوة صغيرة، ثم أخرى. تعلّم بالوتيرة التي تناسبك.','One small step, then another. Learn at your own pace.')}</p><section className="journey-banner"><div><span className="badge demo">{t('الرحلة الأولى','JOURNEY ONE')}</span><h2>{txt(journey)}</h2><p>{t('٦ محطات · بلا استعجال','6 stops · Take your time')}</p></div><Footprints size={58}/></section><ContentState/><div className="journey-path">{[t('لاحظ اللحظة','Notice'),t('خمّن','Take a guess'),t('اكتشف المعنى','Find the meaning'),t('واصل الاكتشاف','Explore further'),t('صل المعاني','Make connections'),t('ختم رحلتك','Your journey stamp')].map((name,i)=>{const reached=canJourney&&(i===0||i<=journeyStep);return <div className={'path-stop stop-'+i+(reached?' unlocked':'')} key={i}><button disabled={!reached} onClick={()=>{setJourneyStep(i);go('journey');}} aria-label={name+(reached?'':t('، أكمل السابقة لفتحها',', complete the previous step to unlock'))}>{i===5?<Stamp/>:reached?<span>{i+1}</span>:<LockKeyhole size={20}/>}</button><div><strong>{name}</strong><small>{i===0&&!canJourney?t('بانتظار نصوص مطابَقة على مصادرها','Awaiting source-verified text'):i===5?t('يُحفظ في جوازك','Saved in your passport'):t('محطة','Stop')+' '+(i+1)}</small></div></div>;})}</div>{review&&<Draft/>}{!canJourney&&!contentLoading?<div className="notice"><ShieldCheck/><p>{t('هذه الرحلة غير متاحة حتى تتوفر النصوص اللازمة من مصادرها.','This journey needs its source-linked texts before it can open.')}</p></div>:canJourney&&<button className="primary" onClick={startJourney}>{review?t('عاين الرحلة للمراجعة','Preview for review'):t('ابدأ الرحلة','Start the journey')}</button>}</>}
 {view==='journey'&&<><div className="step-top"><span>{t('المحطة','Stop')} {journeyStep+1} / 6</span><span>{t('بالوتيرة التي تناسبك','At your own pace')}</span></div><Progress value={(journeyStep+1)/6*100} aria-label={t('تقدم الرحلة','Journey progress')}/>{review&&<Draft/>}{!canJourney?<Empty title={t('نصوص الرحلة غير مكتملة','This journey needs more source text')}/>:<section className="learning-card">
 {journeyStep===0&&<><div className="detail-emblem"><Headphones size={44}/></div><h2>{t('توقّف عند هذه اللحظة.','Pause at this moment.')}</h2>{journeyClaims[0]&&<ClaimView claim={journeyClaims[0]}/>}<button className="primary" onClick={advanceJourney}>{t('تأملت اللحظة','I’ve taken a moment')}</button></>}
 {journeyStep===1&&<><span className="learning-kicker">{t('فضولك بداية الفهم','CURIOSITY COMES FIRST')}</span><h2>{txt(journey.question)}</h2>{journeyClaims[0]&&<ClaimView claim={journeyClaims[0]}/>}<div className="option-stack">{journey.question.options.map(id=><button className={'option '+(answer===id?'selected':'')} key={id} disabled={quizCorrect} onClick={()=>{setAnswer(id);setFeedback('');}}><Icon name={id==='wudu'?'water':'audio'}/>{momentName(id)}{answer===id&&<Check size={20}/>}</button>)}</div>{feedback&&<p className={'feedback '+(quizCorrect?'positive':'')} role="status">{feedback}</p>}<button className="primary" disabled={!answer} onClick={()=>{if(quizCorrect)advanceJourney();else if(answer===journey.question.answer){setQuizCorrect(true);setFeedback(t('وصلت الفكرة. لنكتشف مصدرها.','You made the connection. Let’s find its source.'));haptic();}else setFeedback(t('اقتربت. تأمل النص وجرب اختيارًا آخر.','You’re exploring. Take another look and try a different choice.'));}}>{quizCorrect?t('اكتشف المصدر','Explore the source'):t('تحقّق من اختياري','Check my choice')}</button></>}
 {journeyStep===2&&<><div className="detail-emblem"><BookOpen size={40}/></div><h2>{t('المعنى، ومعه مصدره.','The meaning, with its source.')}</h2>{journeyClaims[0]&&<ClaimView claim={journeyClaims[0]}/>}<button className="primary" onClick={advanceJourney}>{t('واصل الاكتشاف','Keep exploring')}</button></>}
 {journeyStep===3&&<><h2>{t('نوافذ أخرى على اللحظة','More windows into the moment')}</h2>{journeyClaims.slice(1).map(c=><div key={c.claimId}><h3>{momentName(c.momentId)}</h3><ClaimView claim={c}/></div>)}<button className="primary" onClick={advanceJourney}>{t('جرّب ربط المعاني','Try making connections')}</button></>}
 {journeyStep===4&&<><span className="learning-kicker">{t('مطابقة','MAKE A CONNECTION')} {Math.min(matchIndex+1,4)} / 4</span><h2>{t('صل النص بلحظته.','Match the text to its moment.')}</h2>{matchIndex<4?<>{(()=>{const c=journeyClaims.find(c=>c.claimId===journey.matching.pairs[matchIndex].claimId);return c?<ClaimView claim={c}/>:null;})()}<div className="match-options">{journey.matching.pairs.map(pair=><button className="outlined" key={pair.moment} onClick={()=>{if(pair.moment===journey.matching.pairs[matchIndex].moment){setMatchIndex(i=>i+1);setFeedback(t('رابط جميل.','A thoughtful connection.'));haptic();}else setFeedback(t('لننظر إلى النص مرة أخرى.','Let’s look at the text once more.'));}}>{momentName(pair.moment)}</button>)}</div></>:<div className="matched"><Check size={50}/><h3>{t('وصلت كل المعاني.','You connected them all.')}</h3></div>}{feedback&&<p className="feedback" role="status">{feedback}</p>}<button className="primary" disabled={matchIndex<4} onClick={advanceJourney}>{t('إلى ختام الرحلة','Finish the journey')}</button></>}
 {journeyStep===5&&<><div className="finish-stamp"><Stamp size={52}/><span>LAHZA</span></div><h2>{review?t('اكتملت معاينة الرحلة.','Journey preview complete.'):t('صار لك فهمٌ جديد.','A new understanding is yours.')}</h2><p>{review?t('هذه معاينة لمسودة. لا تمنح ختم تعلّم، ولا تغيّر حالة الاعتماد.','This is a draft preview. It awards no learning stamp and changes no review status.'):t('احتفظ بهذه الرحلة في جواز لحظاتك.','Keep this journey in your moment passport.')}</p><button className="primary" onClick={()=>{if(!review&&journeyReady){earn('journey-call-to-prayer','journey',journey.claimIds);save(PROGRESS,5);}go('passport');}}>{review?t('شاهد الجواز','View passport'):t('اختم جوازي','Stamp my passport')}</button></>}
 </section>}</>}
 {view==='passport'&&<><div className="passport-summary"><span><b>{stamps.filter(s=>s.type!=='visit-demo').length}</b> {t('لحظات فهم','moments understood')}</span><span className="badge"><ShieldCheck size={14}/>{t('على جهازك فقط','Only on this device')}</span></div><section className="passport-book" key={page}><div className="passport-top"><Compass size={25}/><span>LAHZA PASSPORT</span><span>{page+1} / 2</span></div><h2>{page===0?t('كل ختم، نافذة جديدة.','Every stamp, a new window.'):t('رحلات وتجارب.','Journeys and encounters.')}</h2><div className="stamp-grid">{(page===0?['adhan','wudu','iqamah','congregational-prayer']:['khutbah','journey-call-to-prayer','visit-demo']).map((id,i)=>{const stampId=id.startsWith('journey')||id==='visit-demo'?id:'moment-'+id,won=stamps.find(s=>s.id===stampId);return <button className={'passport-stamp '+(won?'earned':'locked')+' stamp-'+i} key={id} onClick={()=>{if(id==='visit-demo')go('experiences');else if(id.startsWith('journey'))go('journeys');else openMoment(id);}}><span className="stamp-ring">{id==='visit-demo'?<MapPin size={27}/>:id.startsWith('journey')?<Footprints size={27}/>:<Icon name={id==='wudu'?'water':id==='congregational-prayer'?'people':id==='khutbah'?'book':'audio'} size={27}/>}<strong>{id==='visit-demo'?t('زيارة تجريبية','Demo visit'):id.startsWith('journey')?t('رحلة النداء','Call journey'):momentName(id)}</strong><small>{won?new Intl.DateTimeFormat(ar?'ar-SA-u-nu-latn':'en',{day:'numeric',month:'short',calendar:'gregory'}).format(new Date(won.at)):t('بانتظار لحظتك','WAITING FOR YOU')}</small></span><small className="stamp-help">{id==='visit-demo'?t('نموذج تجريبي موسوم','Labeled demo stamp'):won?t('أضفته إلى فهمك','Added to your understanding'):id.startsWith('journey')?t('أكمل الرحلة لنيل الختم','Complete the journey to earn it'):t('افهم اللحظة لنيل الختم','Explore the source-verified explanation')}</small></button>;})}</div><div className="passport-bottom"><span>لَحْظَة</span><span>••• {String(page+1).padStart(2,'0')} •••</span></div></section><div className="passport-pagination"><button className="outlined" disabled={page===0} onClick={()=>setPage(0)}>{t('الصفحة السابقة','Previous page')}</button><button className="outlined" disabled={page===1} onClick={()=>setPage(1)}>{t('الصفحة التالية','Next page')}</button></div><button className="primary" onClick={async()=>{try{const exported=await exportPassport(stamps.map(s=>({...s,label:s.id==='visit-demo'?t('زيارة تجريبية','Demo visit'):s.id.startsWith('journey')?txt(journey):momentName(s.id.replace('moment-',''))})),prefs.lang);setPassportImage(exported);setToast(t('صورة الجواز جاهزة.','Your passport image is ready.'));}catch{setToast(t('تعذّر إنشاء الصورة. أعد المحاولة.','Could not create the image. Please retry.'));}}}><Share2 size={20}/>{t('شارك جوازك صورة','Share your passport image')}</button><p className="fine-print">{t('جوازك لا يتضمن اسمًا أو موقعًا أو محادثات.','Your passport contains no name, location or conversations.')}</p></>}
 {view==='experiences'&&<><div className="demo-notice"><Ticket size={19}/><p>{demoNotice}</p></div><button className="primary" onClick={askLocation}><MapPin size={20}/>{t('أقرب معلم مناسب','Find a nearby place')}</button><div className="panel city-search"><label htmlFor="city-search">{t('أو ابحث بالمدينة','Or search by city')}</label><input id="city-search" value={citySearch} onChange={e=>setCitySearch(e.target.value)} placeholder={t('اكتب اسم المدينة','Enter a city name')}/>{locationStatus&&<p role="status">{locationStatus}</p>}</div>{citySearch&&!cities.some(c=>[c.ar.toLowerCase(),c.en.toLowerCase()].some(v=>v.includes(citySearch.toLowerCase())))?<Empty title={t('لا توجد نماذج لهذه المدينة.','No sample experiences for this city.')} body={t('جرّب الرياض أو جدة أو المدينة المنورة.','Try Riyadh, Jeddah or Madinah.')}/>:<div className="experience-list">{experience.experiences.map(x=><button className="experience-card" key={x.id} onClick={()=>{setExperienceId(x.id);setBookingStep(0);setDate(upcomingDates[0]);go('booking');}}><span className="experience-art"><Icon name={x.icon} size={48}/></span><span className="experience-copy"><span className="badge demo">{t('بيانات نموذجية','SAMPLE DATA')}</span><strong>{txt(x)}</strong><span><Clock3 size={15}/>{x.duration} {t('دقيقة','minutes')}<Globe2 size={15}/>{t('العربية / English','English / العربية')}</span><small>{t('موقع تجريبي · '+(citySearch||city.ar),'Sample location · '+(citySearch||city.en))}</small></span></button>)}</div>}</>}
 {view==='booking'&&<><div className="demo-notice"><Ticket size={18}/><p>{demoNotice}</p></div><div className="step-top"><span>{t('الخطوة','Step')} {bookingStep+1} / 5</span><span>{[t('التفاصيل','Details'),t('الموعد','Date & time'),t('الأشخاص','Guests'),t('اللغة','Language'),t('المراجعة','Review')][bookingStep]}</span></div><Progress value={(bookingStep+1)/5*100} aria-label={t('تقدم الحجز التجريبي','Demo booking progress')}/><section className="panel booking-panel">
 {bookingStep===0&&<><div className="experience-art"><Icon name={selectedExperience.icon} size={58}/></div><h2>{txt(selectedExperience)}</h2><div className="booking-facts"><p><Clock3/>{selectedExperience.duration} {t('دقيقة نموذجية','sample minutes')}</p><p><MapPin/>{t('موقع تجريبي، '+(citySearch||city.ar),'Sample location, '+(citySearch||city.en))}</p><p><Users/>{t('فريق تجريبي بلا جهة مرتبطة','Sample team, no provider connected')}</p></div><p className="muted">{t('جرّب خطوات الحجز حتى إصدار تذكرة نموذجية. لا تُرسل بياناتك إلى أي جهة.','Try the booking steps through a sample ticket. No information is sent to a provider.')}</p></>}
 {bookingStep===1&&<><h2>{t('متى ترغب بالزيارة؟','When would you like to visit?')}</h2><label htmlFor="booking-date">{t('التاريخ','Date')}</label><input id="booking-date" type="date" min={upcomingDates[0]} value={date} onChange={e=>setDate(e.target.value)}/><label>{t('أوقات نموذجية','Sample times')}</label><div className="time-options">{['10:00','14:00','17:00'].map(s=><button className={'outlined '+(slot===s?'selected':'')} key={s} onClick={()=>setSlot(s)}>{s}</button>)}</div></>}
 {bookingStep===2&&<><div className="detail-emblem"><Users size={40}/></div><h2>{t('كم شخصًا سيشارك؟','How many people?')}</h2><div className="stepper"><button aria-label={t('تقليل العدد','Fewer guests')} disabled={people<=1} onClick={()=>setPeople(p=>p-1)}>−</button><output>{people}</output><button aria-label={t('زيادة العدد','More guests')} disabled={people>=8} onClick={()=>setPeople(p=>p+1)}>+</button></div><p className="fine-print">{t('من شخص واحد إلى ٨ أشخاص في النموذج.','From 1 to 8 guests in this demo.')}</p></>}
 {bookingStep===3&&<><div className="detail-emblem"><Globe2 size={40}/></div><h2>{t('بأي لغة تفضّل اللقاء؟','Which language would you prefer?')}</h2><div className="option-stack">{(['ar','en'] as const).map(l=><button className={'option '+(bookingLang===l?'selected':'')} key={l} onClick={()=>setBookingLang(l)}>{l==='ar'?'العربية':'English'}{bookingLang===l&&<Check/>}</button>)}</div></>}
 {bookingStep===4&&<><h2>{t('راجع تجربتك النموذجية','Review your sample experience')}</h2><dl className="booking-review"><dt>{t('التجربة','Experience')}</dt><dd>{txt(selectedExperience)}</dd><dt>{t('الموعد','Date & time')}</dt><dd>{date} · {slot}</dd><dt>{t('الأشخاص','Guests')}</dt><dd>{people}</dd><dt>{t('اللغة','Language')}</dt><dd>{bookingLang==='ar'?'العربية':'English'}</dd></dl><div className="attached-card"><MessageCircle size={22}/><div><strong>{t('بطاقة الحوار مرفقة','Conversation card attached')}</strong><p>{card.question||t('لم تضف سؤالًا بعد.','No question added yet.')}</p></div><button className="text-button" onClick={()=>setCardOpen(true)}>{t('تعديل','Edit')}</button></div></>}
 <button className="primary" disabled={bookingStep===1&&(!date||date<upcomingDates[0])} onClick={()=>{if(bookingStep<4)setBookingStep(x=>x+1);else {const tk={id:'DEMO-'+(typeof crypto.randomUUID==='function'?crypto.randomUUID().slice(0,6):Date.now().toString(36).slice(-3)+Math.random().toString(36).slice(2,5)).toUpperCase(),experience:experienceId,date,slot,people,language:bookingLang,city:citySearch||city[prefs.lang],card,demo:true};setTicket(tk);go('ticket');}}}>{bookingStep===4?t('أنشئ تذكرة تجريبية','Create a demo ticket'):t('متابعة','Continue')}</button>{bookingStep>0&&<button className="text-button" onClick={()=>setBookingStep(x=>x-1)}>{t('الخطوة السابقة','Previous step')}</button>}</section></>}
 {view==='ticket'&&<><div className="demo-notice"><Ticket/><p>{demoNotice}</p></div>{ticket?<section className="ticket"><span className="ticket-icon"><Ticket size={40}/></span><span className="badge demo">{t('تذكرة تجريبية · ليست حجزًا','DEMO TICKET · NOT A BOOKING')}</span><h2>{txt(selectedExperience)}</h2><div className="ticket-code">{String(ticket.id)}</div><dl className="booking-review"><dt>{t('الموعد','When')}</dt><dd>{String(ticket.date)} · {String(ticket.slot)}</dd><dt>{t('الأشخاص','Guests')}</dt><dd>{String(ticket.people)}</dd><dt>{t('اللغة','Language')}</dt><dd>{ticket.language==='ar'?'العربية':'English'}</dd></dl><p>{t('بطاقة الحوار مرفقة بهذه التذكرة محليًا.','Your conversation card is attached to this ticket locally.')}</p><div className="ticket-dash"/><button className="primary" onClick={()=>{earn('visit-demo','visit-demo',[]);setPage(1);go('passport');}}>{t('أضف ختم الزيارة التجريبي','Add a demo visit stamp')}</button><button className="outlined" onClick={()=>download(ticket,'lahza-demo-ticket.json')}><Download size={18}/>{t('احفظ التذكرة','Save ticket')}</button></section>:<Empty title={t('لم تُنشأ تذكرة بعد.','No ticket created yet.')} action={<button className="primary" onClick={()=>go('experiences')}>{t('استكشف التجارب','Explore experiences')}</button>}/>}</>}
 {view==='settings'&&<><section className="settings-section"><h2>{t('تجربتك','Your experience')}</h2><div className="setting-group"><label>{t('وضع التطبيق','App mode')}</label><div className="segmented">{(['demo','live'] as const).map(m=><button key={m} className={prefs.mode===m?'selected':''} onClick={()=>{patch({mode:m});setDemoStart(Date.now());}}>{m==='demo'?t('عرض توضيحي','Demo'):t('الوقت الفعلي','Live time')}</button>)}</div><p className="fine-print">{prefs.mode==='demo'?t('أوقات معدّة لاستكشاف خصائص التطبيق.','Prepared times for exploring the app.'):t('الوقت الحالي في المدينة المختارة. المواقيت تقريبية.','Current time in the selected city. Prayer times are approximate.')}</p></div><div className="setting-group"><label htmlFor="language">{t('اللغة','Language')}</label><select id="language" value={prefs.lang} onChange={e=>patch({lang:e.target.value as Lang})}><option value="ar">العربية</option><option value="en">English</option></select></div><div className="setting-group"><label htmlFor="city">{t('المدينة','City')}</label><select id="city" value={prefs.city} onChange={e=>patch({city:e.target.value})}>{cities.map(c=><option key={c.id} value={c.id}>{c[prefs.lang]}</option>)}</select></div><div className="setting-group"><label htmlFor="iqamah">{t('الفاصل التقديري حتى الإقامة، بالدقائق','Minutes until iqamah, the call as prayer begins')}</label><input id="iqamah" type="number" min={5} max={60} value={prefs.iqamah} onChange={e=>patch({iqamah:Math.max(5,Math.min(60,Number(e.target.value)||15))})}/><p className="fine-print">{t('تقريبي يختلف بين المساجد. ليس موعدًا مؤكدًا. مدة الصلاة المعروضة تقدير للواجهة أيضًا.','Approximate and varies by mosque. This is not a confirmed time. The displayed prayer interval is also an estimate.')}</p></div><div className="setting-row"><label htmlFor="sound">{t('صوت خفيف عند الختم','A soft sound with each stamp')}</label><Switch id="sound" checked={prefs.sound} onCheckedChange={v=>patch({sound:v})}/></div></section>
 <section className="settings-section"><h2>{t('ما الذي يهمك؟','What interests you?')}</h2><p className="fine-print">{t('أول اختيار هو غايتك الأساسية. لا نستنتج دينك أو مشاعرك.','Your first choice is your main goal. We do not infer your religion or feelings.')}</p><div className="option-stack">{experience.goals.map(g=><button className={'option goal-option '+(prefs.goals.includes(g.id)?'selected':'')} key={g.id} onClick={()=>{const next=prefs.goals.includes(g.id)?prefs.goals.filter(x=>x!==g.id):[...prefs.goals,g.id];if(next.length)patch({goals:next});}}><span className="choice-check">{prefs.goals.includes(g.id)&&<Check size={15}/>}</span><span>{txt(g)}{prefs.goals[0]===g.id&&<small>{t('الغاية الأساسية','Main goal')}</small>}</span></button>)}</div></section>
 <section className="settings-section"><h2>{t('الثقة والمراجعة','Trust and review')}</h2>{[{id:'privacy',ar:'الخصوصية',en:'Privacy',I:ShieldCheck},{id:'about',ar:'عن التطبيق وحدوده',en:'About and limitations',I:BookOpen},{id:'impact',ar:'أثر السؤال',en:'Question impact',I:MessageCircle}].map(x=><button className="settings-link" key={x.id} onClick={()=>go(x.id as View)}><x.I size={21}/>{txt(x)}<span>{ar?<ChevronLeft size={18}/>:<ChevronRight size={18}/>}</span></button>)}<div className="setting-row"><div><label htmlFor="review-mode">{t('وضع المراجع','Reviewer mode')}</label><p className="fine-print">{t('اعرض المسودات في سياقها. لا يغيّر هذا اعتمادها.','See drafts in context. This does not approve them.')}</p></div><Switch id="review-mode" checked={review} onCheckedChange={onReview}/></div><a className="settings-link" href="https://git.chatgpt-team.site/d9bc866c-c3a9-4e62-93b2-623841d451d0/appgprj_6ac1a9cc50288191842255ed92d1e8e7.git" target="_blank" rel="noreferrer"><BookOpen size={21}/>{t('مستودع الكود (خاص)','Source repository (private)')}<ExternalLink size={16}/></a><a className="settings-link" href="/downloads/lahza-source-v0.6.2.zip"><Download size={21}/>{t('تنزيل كود الإصدار','Download version source')}</a></section><p className="version">LAHZA 0.6.2</p></>}
 {view==='privacy'&&<section className="panel prose"><ShieldCheck className="large-symbol"/><h2>{t('بيانات قليلة، بوضوح.','Less data, clearly explained.')}</h2><p>{t('لا حساب. يُرسل ما تكتبه عند الاكتشاف الذكي، أو عند وجود مصادر لسؤالك، إلى خدمة ذكاء اصطناعي لمعالجته. عند غياب المصادر يتوقف السؤال دون استدعاء النموذج.','No account. Your text is sent to an AI service when you use discovery or when source-verified sources are available for your question. With no sources, the question stops without a model call.')}</p><p>{t('يُطلب موقعك عند ضغط «أقرب معلم مناسب» فقط. يُستخدم على جهازك لاختيار أقرب مدينة من الدليل التجريبي، ولا يُرسل ولا يُحفظ.','Location is requested only when you tap “Find a nearby place”. It is used on your device to find the nearest city in the sample directory. It is neither sent nor saved.')}</p><p>{t('جوازك، بطاقتك، اختياراتك وآخر ٢٠٠ سجل تفاعل محفوظة في هذا المتصفح حتى تحذفها أو تمسح بياناته. لا يوجد ربط بين الأجهزة.','Your passport, card, preferences and last 200 interaction records stay in this browser until you delete them or clear its data. There is no cross-device sync.')}</p><h3>{t('ماذا يحتفظ به الخادم؟','What does the server retain?')}</h3><p>{t('التطبيق لا يكتب نص المحادثة في قاعدة بيانات على الخادم؛ لا توجد مدة احتفاظ تطبيقية للنص. سجل التشغيل يتضمن وقت الاستدعاء وحالته ومدته ومعرّفه دون نص السؤال. مدة احتفاظ منصة الاستضافة بهذه السجلات ومزوّد الذكاء الاصطناعي ببيانات المعالجة غير متحققة لهذا الحساب، ولا ندّعي رقمًا.','The app does not write conversation text to a server database. No application retention period is configured for that text. Operational logs include call time, status, duration and request ID, without question text. Hosting and AI-provider retention settings have not been verified for this account; we do not claim a duration.')}</p><p>{t('طلبات النموذج تستخدم store:false. هذا لا يثبت عدم وجود سجلات لدى المزوّد. الحجز نموذج محلي ولا يُرسل إلى جهة خارجية.','Model requests use store:false. This does not establish that the provider retains no logs. Booking is a local demo and is not sent to a third party.')}</p><button className="outlined danger" onClick={()=>{if(window.confirm(t('حذف الجواز والبطاقة والسجلات والاختيارات من هذا الجهاز؟','Delete the passport, card, logs and preferences from this device?'))){[PREFS,STAMPS,CARD,LOG,PROGRESS].forEach(k=>localStorage.removeItem(k));sessionStorage.removeItem('lahza-dialogues-v030');setPrefs(defaults);setStamps([]);setRows([]);setCard({observation:'',question:'',explanations:[],sources:[]});setReview(false);setMessages([]);setOnboarding(0);go('now');}}}>{t('امسح بياناتي من هذا الجهاز','Clear my data from this device')}</button></section>}
 {view==='about'&&<section className="panel prose"><div className="detail-emblem"><Compass size={44}/></div><h2>{t('فهم ما يحدث، لحظة بلحظة.','Understand a moment at a time.')}</h2><p>{t('لحظة نافذة لفهم ما تراه وتسمعه في حياة المسلمين، من نصوص مطابَقة على مصادرها. لا يستنتج التطبيق دينك أو مشاعرك، ولا يقدّم فتوى.','LAHZA opens a window onto what you see and hear in Muslim life, using source-verified text. It does not infer your religion or feelings and does not give religious rulings.')}</p><div className="notice"><ShieldCheck/><p>{t('المتاح للزائر الآن: '+(content?.approvedCount||0)+' جملة مطابَقة على مصدرها. المسودات: '+(content?.pendingCount||0)+'.','Currently available to visitors: '+(content?.approvedCount||0)+' source-verified sentences. Drafts: '+(content?.pendingCount||0)+'.')}</p></div><p>{t('المواقيت تقريبية. التعرف على الوصف احتمال يحتاج قرائن، وليس إثباتًا لهوية الحدث. لا نحلل تسجيلًا صوتيًا أو صورة في هذا الإصدار.','Times are approximate. Discovery proposes a possibility supported by your observations; it does not prove an event’s identity. This version does not analyze audio recordings or images.')}</p><p>{t('نافذة الأذان نصّية بلا صوت، وتعرض الكلمات بترتيبها وتكرارها من المصدر. التجارب والحجز والتذاكر نماذج موسومة.','The adhan window is text-only, with the words in the source’s order and repetitions. Experiences, bookings and tickets are labeled demos.')}</p><p className="fine-print">{t('رسم مسجد تخيّلي مولّد لهذا التطبيق؛ لا يمثّل معلمًا محددًا.','An AI-generated imaginary mosque illustration; it does not depict a specific landmark.')} · Tajawal · Lucide</p><p className="version">LAHZA 0.6.2</p></section>}
 {view==='impact'&&<><p className="lead">{t('مسار أسئلتك، محفوظ على جهازك.','Your questions, kept on your device.')}</p><div className="impact-summary"><div><b>{rows.length}</b><span>{t('تفاعل مسجل','logged interactions')}</span></div><div><b>{stamps.filter(x=>x.type==='moment').length}</b><span>{t('لحظات فهم','moments understood')}</span></div></div>{rows.length?<><button className="primary" onClick={()=>download({version:'0.6.2',exportedAt:new Date().toISOString(),records:rows,legacy:readConversations()},'lahza-my-complete-log.json')}><Download size={19}/>{t('نزّل سجلي كاملًا','Download my complete log')}</button><div className="impact-list">{[...rows].reverse().map((r,i)=><details className="panel" key={i}><summary><span>{r.type==='chat'?t('محادثة','Conversation'):t('اكتشاف','Discovery')}</span><time>{new Intl.DateTimeFormat(ar?'ar-SA-u-nu-latn':'en',{hour:'2-digit',minute:'2-digit',day:'numeric',month:'short',calendar:'gregory'}).format(new Date(r.at))}</time></summary><p dir="auto">{r.input}</p><p>{t('نتيجة محفوظة في السجل القابل للتنزيل.','The result is included in your downloadable log.')}</p></details>)}</div></>:<Empty title={t('سؤالك الأول بداية الأثر.','Your first question starts the story.')} body={t('ستظهر هنا رحلات الاكتشاف والمحادثات.','Discovery sessions and conversations will appear here.')} action={<button className="primary" onClick={()=>go('discover')}>{t('اكتشف لحظة','Discover a moment')}</button>}/>}</>}
 {busy&&view==='discover'&&<div className="skeletons" role="status" aria-label={t('جارٍ فهم الوصف','Considering your description')}><div/><div/></div>}
 {requestError&&<div className="error-state" role="alert"><p>{requestError}</p><button className="outlined" disabled={busy} onClick={()=>lastRequest.current?.()}>{t('إعادة المحاولة','Try again')}</button></div>}
 </main>
 <nav className="bottom-nav" aria-label={t('التنقل الرئيسي','Main navigation')}>{navItems.map(n=><button key={n.id} className={view===n.id?'active':''} aria-current={view===n.id?'page':undefined} onClick={()=>go(n.id as View)}><span><n.I size={23}/></span><strong>{txt(n)}</strong></button>)}</nav>
 </>}
 <Sheet open={!!passportImage} onOpenChange={v=>{if(!v&&passportImage){URL.revokeObjectURL(passportImage.url);setPassportImage(null);}}}><SheetContent side="bottom" className="lahza-sheet" closeLabel={t('إغلاق','Close')} dir={ar?'rtl':'ltr'}><SheetTitle>{t('صورة جوازك','Your passport image')}</SheetTitle><SheetDescription>{t('احفظ الصورة أو شاركها حين ترغب.','Save the image or share it when you wish.')}</SheetDescription>{passportImage&&<><img src={passportImage.url} alt={t('صورة جواز لحظة','LAHZA passport image')} style={{width:'100%',maxHeight:400,objectFit:'contain',borderRadius:18}}/><a className="primary link-button" href={passportImage.url} download="lahza-passport.png"><Download size={20}/>{t('احفظ الصورة','Save image')}</a>{typeof navigator!=='undefined'&&navigator.canShare?.({files:[passportImage.file]})&&<button className="outlined" onClick={()=>navigator.share({files:[passportImage.file],title:'LAHZA Passport'}).catch(()=>{})}><Share2 size={20}/>{t('مشاركة','Share')}</button>}</>}</SheetContent></Sheet>
 <Sheet open={!!source} onOpenChange={v=>!v&&setSource(null)}><SheetContent side="bottom" className="lahza-sheet" closeLabel={t('إغلاق','Close')} dir={ar?'rtl':'ltr'}><SheetTitle>{source==='calendar'?t('موعد تقريبي','An approximate date'):t('المصدر وراء المعنى','The source behind the meaning')}</SheetTitle><SheetDescription>{source==='calendar'?t('تقريبي وفق تقويم أم القرى، وليس إعلانًا رسميًا للمناسبة.','Approximate, based on the Umm al-Qura calendar. This is not an official announcement.'):t('يمكنك فتح المرجع الأصلي بنفسك.','You can open the original reference.')}</SheetDescription>{source==='calendar'?<a className="primary link-button" href="https://www.ummulqura.org.sa/" target="_blank" rel="noreferrer">{t('افتح تقويم أم القرى','Open the Umm al-Qura calendar')}</a>:(()=>{const s=content?.sources.find(s=>s.id===source);return s?<><span className="source-id">{s.id}</span><h3>{ar?s.title_ar:s.title_en}</h3>{review&&<Draft/>}<a className="primary link-button" href={s.url} target="_blank" rel="noreferrer">{t('افتح المرجع','Open the reference')}<ExternalLink size={18}/></a></>:<p>{t('المرجع غير متاح حاليًا.','The reference is currently unavailable.')}</p>;})()}</SheetContent></Sheet>
 <Sheet open={adhanOpen} onOpenChange={setAdhanOpen}><SheetContent side="bottom" className="lahza-sheet adhan-sheet" closeLabel={t('إغلاق','Close')} dir={ar?'rtl':'ltr'}><SheetTitle>{t('افهم الأذان الذي تسمعه','Understand the call to prayer (adhan)')}</SheetTitle><SheetDescription>{t('كلمات الأذان بترتيبها وتكرارها في المصدر.','The words of the adhan in the source’s order and repetitions.')}</SheetDescription><span className="badge demo"><VolumeX size={15}/>{t('وضع نصّي بلا صوت','Text mode · No audio')}</span>{visiblePhrases.length?<><div className="phrase-progress"><span dir="ltr">{phraseIndex+1} / {visiblePhrases.length}</span><span>{t('التكرار','Repetition')} <bdi dir="ltr">{visiblePhrases[phraseIndex]?.repetition} / {visiblePhrases[phraseIndex]?.total}</bdi></span></div><Progress value={(phraseIndex+1)/visiblePhrases.length*100} aria-label={t('تقدم قراءة الأذان','Adhan reading progress')}/><div className="phrase-reader">{visiblePhrases.slice(Math.max(0,phraseIndex-1),phraseIndex+2).map(p=>{const i=visiblePhrases.indexOf(p);return <button className={'phrase '+(i===phraseIndex?'current':'')} key={p.id} onClick={()=>selectPhrase(i)}><strong lang="ar" dir="rtl">{p.claim.text_ar}</strong>{i===phraseIndex&&!ar&&<span>{p.claim.text_en}</span>}</button>;})}</div>{visiblePhrases[phraseIndex]&&<div className="phrase-source"><Verified/><SourceLinks ids={visiblePhrases[phraseIndex].claim.sourceIds}/></div>}<div className="two-buttons"><button className="outlined" disabled={phraseIndex===0} onClick={()=>selectPhrase(phraseIndex-1)}>{t('السابقة','Previous')}</button><button className="primary" disabled={phraseIndex===visiblePhrases.length-1} onClick={()=>selectPhrase(phraseIndex+1)}>{t('العبارة التالية','Next phrase')}</button></div></>:<Empty title={t('النص غير متاح حاليًا.','The text is not available yet.')}/>}<button className="outlined" onClick={()=>{setAdhanOpen(false);openMoment('adhan');}}>{t('استكشف نصوص الأذان المتاحة','Explore available adhan content')}</button></SheetContent></Sheet>
 <Sheet open={cardOpen} onOpenChange={v=>{setCardOpen(v);if(!v)save(CARD,card);}}><SheetContent side="bottom" className="lahza-sheet card-sheet" closeLabel={t('إغلاق','Close')} dir={ar?'rtl':'ltr'}><SheetTitle>{t('بطاقة للحوار','A card for a conversation')}</SheetTitle><SheetDescription>{t('احتفظ بفضولك. شارك البطاقة بنفسك حين ترغب.','Keep your curiosity. Share this card yourself when you wish.')}</SheetDescription><label>{t('ما لاحظته','What I noticed')}<textarea value={card.observation} maxLength={1200} onChange={e=>setCard({...card,observation:e.target.value})}/></label><label>{t('السؤال الذي أود طرحه','What I’d like to ask')}<textarea value={card.question} maxLength={1200} onChange={e=>setCard({...card,question:e.target.value})}/></label>{card.explanations.length>0&&<div><h3>{t('ما فهمته من المصادر','What I learned from sources')}</h3>{card.explanations.map((x,i)=>{const c=content?.claims.find(c=>passed(c.reviewStatus)&&(c.text_ar===x||c.text_en===x));return c?<ClaimView key={i} claim={c}/>:null;})}</div>}<p className="fine-print">{t('محفوظة على جهازك. لا تُرسل تلقائيًا.','Kept on your device. Never sent automatically.')}</p><button className="primary" onClick={()=>{if(save(CARD,card)){setCardOpen(false);setToast(t('حُفظت بطاقتك.','Your card is saved.'));}}}>{t('احفظ بطاقتي','Save my card')}</button><button className="outlined" onClick={()=>download({version:'0.6.2',...card},'lahza-conversation-card.json')}><Download size={18}/>{t('نزّل نسخة','Download a copy')}</button></SheetContent></Sheet>
 {toast&&<div className="toast" role="status">{toast}</div>}{celebrate&&<div className="celebration" role="status"><div className="celebration-stamp"><Stamp size={45}/><strong>{celebrate==='visit-demo'?t('ختم تجريبي','Demo stamp'):t('لحظة تستحق أن تبقى','A moment worth keeping')}</strong><Sparkles size={24}/></div></div>}
 </div>;
}
