'use client';
import {useEffect,useImperativeHandle,useRef,useState,type Ref} from 'react';
import {BookOpen,Download,Stamp} from 'lucide-react';
import {Sheet,SheetContent,SheetDescription,SheetTitle} from '@/components/ui/sheet';
import {MeaningBranch} from '@/components/moment-content';
import type {contentPayload} from '@/lib/content-library';
import {personalId,type PersonalMoment} from '@/lib/personal-moments';
import {exportSouvenir} from '@/lib/souvenir-image';
import {cities} from '@/lib/prayer-clock';
type Content=ReturnType<typeof contentPayload>;
type Stage='before'|'meaning'|'after'|'saved';
type Session={stage:Stage;record:PersonalMoment};
export type PersonalMomentHandle={open:(stage:Stage,momentId?:string,record?:PersonalMoment)=>void;reset:()=>void};
export default function PersonalMomentFlow({language,city,content,records,onSave,onListen,onEarn,controller,allowLearning=true}:{language:'ar'|'en';city:string;content:Content|null;records:PersonalMoment[];onSave:(record:PersonalMoment)=>boolean;onListen:()=>void;onEarn:(id:string,claimIds:string[])=>void;controller:Ref<PersonalMomentHandle>;allowLearning?:boolean}){
 const [session,setSession]=useState<Session|null>(null),[image,setImage]=useState<{url:string;file:File}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const epoch=useRef(0),ar=language==='ar',t=(a:string,e:string)=>ar?a:e;
 function reset(){epoch.current++;setSession(null);setImage(null);setBusy(false);setError('');}
 useEffect(()=>()=>{if(image)URL.revokeObjectURL(image.url);},[image]);
 useEffect(()=>()=>{epoch.current++;},[]);
 useImperativeHandle(controller,()=>({reset,open(stage,momentId='adhan',existing){epoch.current++;setImage(null);setBusy(false);setError('');const saved=existing||records.find(r=>r.id===personalId(momentId,city));setSession({stage,record:saved||{id:personalId(momentId,city),momentId,city,before:'',after:'',language,at:new Date().toISOString(),learned:false}});}}));
 const record=session?.record,claims=content?.claims.filter(c=>c.momentId===record?.momentId&&c.branchId.endsWith('-meaning')&&['approved','approved_with_edits'].includes(c.reviewStatus))||[];
 const cityName=cities.find(c=>c.id===record?.city)?.[language]||'',moment=content?.moments.find(m=>m.id===record?.momentId),momentName=moment?(ar?moment.name_ar:moment.name_en):'';
 function update(field:'before'|'after',value:string){if(session)setSession({...session,record:{...session.record,[field]:value.slice(0,360),language}});}
 function persist(next:PersonalMoment){if(!onSave(next)){setError(t('تعذّر الحفظ. بقي نصك هنا، أعد المحاولة.','Could not save. Your text is still here. Please retry.'));return false;}setError('');return true;}
 function begin(saveBefore:boolean){if(!session)return;if(saveBefore&&!persist({...session.record,at:new Date().toISOString()}))return;setSession(null);onListen();}
 async function makeImage(){if(!record||busy)return;setBusy(true);setError('');const started=epoch.current;try{const output=await exportSouvenir(record,language,cityName,momentName);if(started!==epoch.current){URL.revokeObjectURL(output.url);return;}setImage(output);}catch{if(started===epoch.current)setError(t('تعذّر إنشاء الصورة. أعد المحاولة.','Could not create the image. Please retry.'));}finally{if(started===epoch.current)setBusy(false);}}
 return <Sheet open={!!session} onOpenChange={v=>{if(!v)reset();}}><SheetContent side="bottom" className="lahza-sheet reflection-sheet" closeLabel={t('إغلاق','Close')} dir={ar?'rtl':'ltr'}><SheetTitle>{session?.stage==='before'?t('قبل أن تستمع','Before you listen'):session?.stage==='meaning'?(record?.momentId==='adhan'?t('ماذا وراء هذه الكلمات؟','What is behind these words?'):t('ماذا وراء هذه اللحظة؟','What is behind this moment?')):session?.stage==='after'?t('ما الذي بقي معك؟','What will you take with you?'):t('لحظة فهم من '+cityName,'A moment of understanding from '+cityName)}</SheetTitle><SheetDescription>{session?.stage==='meaning'?t('تأمل المعنى بالوتيرة التي تناسبك.','Explore the meaning at your own pace.'):t('تأملك الشخصي، محفوظ على هذا الجهاز فقط.','Your personal reflection, saved only on this device.')}</SheetDescription>
 {record&&session?.stage==='before'&&<><label htmlFor="reflection-before">{t('ماذا كنت تظن أن هذا النداء يعني؟','What did you think this call meant?')} <small>{t('اختياري','Optional')}</small></label><textarea id="reflection-before" dir="auto" rows={3} maxLength={360} value={record.before} onChange={e=>update('before',e.target.value)} placeholder={t('اكتب بكلماتك…','In your own words…')}/><button className="primary" onClick={()=>begin(true)}>{t('احفظ وابدأ الاستماع','Save and start listening')}</button><button className="text-button" onClick={()=>begin(false)}>{t('ابدأ الاستماع دون إجابة','Listen without answering')}</button></>}
 {record&&session?.stage==='meaning'&&<><MeaningBranch momentId={record.momentId} content={content} language={language}/>{!claims.length&&<p role="status">{t('المعنى غير متاح حاليًا. أعد فتح هذه النافذة بعد تحميل المحتوى.','The meaning is unavailable right now. Reopen this window after the content loads.')}</p>}<button className="primary" disabled={!claims.length||!allowLearning} onClick={()=>{const next={...record,learned:true,at:new Date().toISOString()};if(persist(next)){onEarn(record.momentId,claims.map(c=>c.claimId));setSession({stage:'after',record:next});}}}>{t('تأملت المعنى، وأريد حفظ أثره','I explored the meaning. Keep this moment')}</button></>}
 {record&&session?.stage==='after'&&<>{record.before&&<div className="reflection-before"><small>{t('قبل التجربة، كتبت','Before exploring, you wrote')}</small><p dir="auto">{record.before}</p></div>}<label htmlFor="reflection-after">{t('ما الذي فهمته الآن؟','What do you understand now?')} <small>{t('اختياري','Optional')}</small></label><textarea id="reflection-after" rows={4} dir="auto" maxLength={360} value={record.after} onChange={e=>update('after',e.target.value)} placeholder={t('قد يكون فهمك تغيّر، أو بقي لديك سؤال…','Your understanding may have changed, or you may still have a question…')}/><button className="primary" onClick={()=>{const next={...record,at:new Date().toISOString()};if(persist(next))setSession({stage:'saved',record:next});}}>{t('احفظ لحظتي','Save my moment')}</button><button className="text-button" onClick={()=>{if(persist(record))setSession({stage:'saved',record});}}>{t('احتفظ باللحظة دون إجابة','Keep the moment without answering')}</button></>}
 {record&&session?.stage==='saved'&&<><article className="souvenir-card"><img src="/art/lahza-skyline.svg" alt=""/><div><span className="eyebrow">لَحْظَة · LAHZA</span><h2>{momentName}</h2>{record.before&&<><small>{t('قبل التجربة','Before exploring')}</small><p dir="auto">{record.before}</p></>}{record.after&&<><small>{t('ما فهمته الآن','What I understand now')}</small><p dir="auto">{record.after}</p></>}<p className="fine-print">{t('تأمل شخصي كتبه الزائر','A personal reflection written by the visitor')}</p>{record.learned&&<span className="souvenir-stamp"><Stamp size={23}/>{t('ختم تعلّم','Learning stamp')}</span>}</div></article>{image?<><img className="souvenir-preview" src={image.url} alt={t('صورة بطاقة الذكرى','Souvenir image preview')}/><a className="primary link-button" href={image.url} download="lahza-moment.png"><Download size={20}/>{t('نزّل صورة الذكرى','Download souvenir image')}</a></>:<button className="primary" disabled={busy} onClick={()=>void makeImage()}><Download size={20}/>{busy?t('جارٍ إعداد الصورة…','Preparing image…'):t('جهّز صورة الذكرى','Create souvenir image')}</button>}<button className="outlined" onClick={()=>{setImage(null);setSession({stage:'after',record});}}>{t('عدّل تأملي','Edit my reflection')}</button><button className="text-button" onClick={reset}>{t('تم','Done')}</button></>}
 {error&&<p role="alert" className="error-state">{error}</p>}
 </SheetContent></Sheet>;
}
export function PersonalMomentList({records,language,onOpen}:{records:PersonalMoment[];language:'ar'|'en';onOpen:(record:PersonalMoment)=>void}){
 const ar=language==='ar';return <section className="panel personal-moments"><h2>{ar?'لحظات بقي أثرها':'Moments to remember'}</h2>{records.length?<div className="personal-moment-list">{[...records].reverse().map(r=><button className="question-button" key={r.id} onClick={()=>onOpen(r)}><BookOpen size={20}/><span><strong>{ar?'لحظة فهم من ':'A moment from '}{cities.find(c=>c.id===r.city)?.[language]}</strong><small>{new Intl.DateTimeFormat(ar?'ar-SA-u-nu-latn':'en',{day:'numeric',month:'short',calendar:'gregory'}).format(new Date(r.at))}</small></span><Download size={18}/></button>)}</div>:<p>{ar?'بعد الاستماع، تأمل المعنى واحتفظ بلحظتك هنا.':'After listening, explore the meaning and keep your moment here.'}</p>}</section>;
}
