import {Coordinates,CalculationMethod,PrayerTimes} from 'adhan';
export const cities=[{id:'riyadh',ar:'الرياض',en:'Riyadh',lat:24.7136,lng:46.6753,zone:'Asia/Riyadh'},{id:'jeddah',ar:'جدة',en:'Jeddah',lat:21.4858,lng:39.1925,zone:'Asia/Riyadh'},{id:'makkah',ar:'مكة المكرمة',en:'Makkah',lat:21.4225,lng:39.8262,zone:'Asia/Riyadh'},{id:'madinah',ar:'المدينة المنورة',en:'Madinah',lat:24.4672,lng:39.6024,zone:'Asia/Riyadh'},{id:'dammam',ar:'الدمام',en:'Dammam',lat:26.4207,lng:50.0888,zone:'Asia/Riyadh'}];
export type City=typeof cities[number];
export const prayerKeys=['fajr','dhuhr','asr','maghrib','isha'] as const;
export const prayerNames={fajr:{ar:'الفجر',en:'Fajr'},dhuhr:{ar:'الظهر',en:'Dhuhr'},asr:{ar:'العصر',en:'Asr'},maghrib:{ar:'المغرب',en:'Maghrib'},isha:{ar:'العشاء',en:'Isha'}};
export const prayerMeanings={fajr:'dawn',dhuhr:'midday',asr:'afternoon',maghrib:'sunset',isha:'night'};
export const scenarioNames=[{id:'before',ar:'قبل المغرب',en:'Before sunset'},{id:'adhan',ar:'أذان الظهر',en:'Midday call'},{id:'between',ar:'قبل الإقامة',en:'Before prayer'},{id:'prayer',ar:'الصلاة الآن',en:'Prayer time'},{id:'friday',ar:'ظهر الجمعة',en:'Friday noon'},{id:'next',ar:'بين صلاتين',en:'Between prayers'}];
export function dayParts(date:Date,zone:string){return new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date).reduce((a,p)=>(a[p.type]=p.value,a),{} as Record<string,string>);}
export function timesFor(date:Date,city:City){const p=dayParts(date,city.zone),day=new Date(+p.year,+p.month-1,+p.day,12);const params=CalculationMethod.UmmAlQura();const hijri=new Intl.DateTimeFormat('en-u-ca-islamic-umalqura',{month:'numeric',timeZone:city.zone}).format(date);if(Number(hijri)===9)params.ishaInterval=120;const times=new PrayerTimes(new Coordinates(city.lat,city.lng),day,params);return prayerKeys.map(key=>({key,date:times[key],...prayerNames[key]}));}
export function simulatedDate(scenario:string,city:City,iqamah:number,_elapsed=0){const date=new Date(scenario==='friday'?'2026-10-09T09:00:00Z':'2026-10-05T09:00:00Z'),t=timesFor(date,city);const target=scenario==='before'?t[3]:scenario==='next'?t[2]:t[1];const offset=scenario==='before'?-4:scenario==='adhan'?0:scenario==='between'?5:scenario==='prayer'?iqamah+2:scenario==='friday'?1:-70;return new Date(target.date.getTime()+offset*60000);}
export function clockState(date:Date,city:City,iqamah:number){const t=timesFor(date,city);const next=t.find(x=>x.date>date)||timesFor(new Date(date.getTime()+86400000),city)[0];const prev=[...t].reverse().find(x=>x.date<=date);const mins=prev?(date.getTime()-prev.date.getTime())/60000:Infinity;const friday=new Intl.DateTimeFormat('en',{weekday:'short',timeZone:city.zone}).format(date)==='Fri';const state=friday&&prev?.key==='dhuhr'&&mins<30?'friday':mins<3?'adhan':mins<iqamah?'between':mins<iqamah+12?'prayer':(next.date.getTime()-date.getTime())/60000<=10?'before':'next';return {times:t,next,previous:prev,state,remaining:Math.max(0,Math.floor((next.date.getTime()-date.getTime())/1000))};}
export function nextOccasion(date:Date,city:City){const fmt=new Intl.DateTimeFormat('en-u-ca-islamic-umalqura',{timeZone:city.zone,month:'numeric',day:'numeric'});const labels=[{month:9,day:1,ar:'رمضان',en:'Ramadan'},{month:10,day:1,ar:'عيد الفطر',en:'Eid al-Fitr'},{month:12,day:10,ar:'عيد الأضحى',en:'Eid al-Adha'}];for(let i=1;i<=370;i++){const d=new Date(date.getTime()+i*86400000);const p=fmt.formatToParts(d);const m=+p.find(x=>x.type==='month')!.value,day=+p.find(x=>x.type==='day')!.value;const label=labels.find(x=>x.month===m&&x.day===day);if(label)return {...label,date:d,days:i};}return null;}
