// Real HTTP/model smoke test. Run deliberately: it makes paid model calls.
// Synthetic descriptions only; no API key is needed by this client.
import {writeFileSync,mkdirSync} from 'node:fs';
const base=process.env.LAHZA_BASE_URL||'https://lahza-discovery.stemlama.chatgpt.site';
const report={kind:'synthetic live smoke test, not user research',at:new Date().toISOString(),base,blocked:null,scenarios:[]};
const scenes=[
 {id:'adhan-ar',language:'ar',description:'سمعت صوتًا بالعربية في مكان عام',answers:{Q1:'مكبرات خارج مبنى له برج',Q2:'نحو ثلاث دقائق',Q3:'صوت واحد بعبارات منغمة بينها وقفات',Q4:'أتذكر عبارة الله أكبر، وعبارة حي على الصلاة',Q5:'لم أسمع نداء قبله',Q7:'اتجه بعض الناس نحو المبنى'},allowConfirmation:true},
 {id:'shop-ar',language:'ar',description:'رجل يرتل بالعربية داخل متجر',answers:{Q1:'من جهاز داخل المتجر',Q2:'استمر طوال وجودي في المتجر، أكثر من عشر دقائق',Q3:'قراءة متصلة',Q4:'لا أتذكر أي كلمة',Q7:'واصل الناس التسوق'},allowConfirmation:false}
];
async function request(body){const response=await fetch(new URL('/api/discovery',base),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:AbortSignal.timeout(50000)});const text=await response.text();let data;try{data=JSON.parse(text);}catch{throw Error('HTTP '+response.status+': non-JSON response, application endpoint not reached');}if(!response.ok)throw Error('HTTP '+response.status+': '+(data.error||'request failed'));return data;}
try{for(const scene of scenes){const run={id:scene.id,description:scene.description,turns:[],outcome:'unfinished'};report.scenarios.push(run);let action='start',input=scene.description,token='',asked=0;for(let i=0;i<4;i++){const d=await request({action,text:input,language:scene.language,token});token=d.token;run.turns.push({input,action,decision:d.decision,model:d.model,requestId:d.requestId,version:d.version});if(d.kind!=='decision')throw Error('Unexpected response');if(d.decision.decision==='ask'){if(++asked>2)throw Error('Question budget exceeded');input=scene.answers[d.decision.question_id]||'لا أعرف';action='reply';continue;}if(d.decision.decision==='confirm'){if(!scene.allowConfirmation){run.outcome='review_required_unexpected_adhan_confirmation';break;}for(const topic of ['purpose','words','response']){const e=await request({action:topic==='purpose'?'accept':'explain',text:topic==='purpose'?'نعم، أريد استكشاف الأذان':topic,topic,depth:'30',token});token=e.token;run.turns.push({action:topic,answer:e.result?.answer,claims:e.result?.claims,gate:e.result?.gate,model:e.model,requestId:e.requestId,version:e.version});if(e.kind!=='explanation'||e.result.gate.decision!=='Pass')throw Error('Explanation did not pass evidence gate');}run.outcome='confirmed_and_three_topics_explored';break;}run.outcome='stopped_'+d.decision.stop_type;break;}}}catch(error){report.blocked=String(error.message||error);process.exitCode=1;}
mkdirSync('outputs',{recursive:true});writeFileSync('outputs/live-smoke.json',JSON.stringify(report,null,2));console.log(JSON.stringify({blocked:report.blocked,scenarios:report.scenarios.map(x=>({id:x.id,outcome:x.outcome,turns:x.turns.length})),report:'outputs/live-smoke.json'}));
