import fs from 'node:fs';import path from 'node:path';import vm from 'node:vm';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const root=process.cwd(),out=root+'/docs/release-0.6.6-audit';fs.mkdirSync(out,{recursive:true});
const require=createRequire(root+'/package.json'),ts=require('typescript'),React=require('react'),jsx=require('react/jsx-runtime');
let active;const cache=new Map();
const eq=(a,b)=>a?.length===b?.length&&a.every((v,i)=>Object.is(v,b[i]));
const hooks={...React,useId:()=>"test-only-id",useState(init){const r=active,i=r.cursor++;if(!r.hooks[i])r.hooks[i]={value:typeof init==='function'?init():init};return [r.hooks[i].value,v=>{const next=typeof v==='function'?v(r.hooks[i].value):v;if(!Object.is(next,r.hooks[i].value)){r.hooks[i].value=next;r.dirty=true;}}];},useRef(init){const r=active,i=r.cursor++;return (r.hooks[i]??={current:init});},useMemo(fn,deps){const r=active,i=r.cursor++;if(!r.hooks[i]||!eq(deps,r.hooks[i].deps))r.hooks[i]={value:fn(),deps};return r.hooks[i].value;},useEffect(fn,deps){const r=active,i=r.cursor++;if(!r.hooks[i]||!eq(deps,r.hooks[i].deps)){const old=r.hooks[i];r.effects.push(()=>{old?.cleanup?.();r.hooks[i]={deps,cleanup:fn()};});}}};
const wrappers={Sheet:p=>p.open?jsx.jsxs('test-sheet',{children:[jsx.jsx('button',{'data-close-sheet':true,onClick:()=>p.onOpenChange(false),children:'Close test sheet'}),p.children]}):null,SheetContent:p=>jsx.jsx('section',{...p}),SheetTitle:p=>jsx.jsx('h2',{...p}),SheetDescription:p=>jsx.jsx('p',{...p}),Progress:p=>jsx.jsx('progress',{...p}),Switch:p=>jsx.jsx('input',{...p,type:'checkbox',onChange:e=>p.onCheckedChange(e.target.checked)})};
function load(file){const full=path.resolve(root,file);if(cache.has(full))return cache.get(full).exports;if(full.endsWith('.json'))return JSON.parse(fs.readFileSync(full));const module={exports:{}};cache.set(full,module);const code=ts.transpileModule(fs.readFileSync(full,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText;
 const localRequire=id=>{if(id==='react')return hooks;if(id==='lucide-react')return new Proxy({},{get:(_,key)=>key==='__esModule'?true:()=>null});if(id.startsWith('@/components/ui/'))return wrappers;if(!id.startsWith('.')&&!id.startsWith('@/'))return require(id);const base=id.startsWith('@/')?path.join(root,id.slice(2)):path.resolve(path.dirname(full),id);const p=[base,base+'.ts',base+'.tsx',base+'.json'].find(p=>fs.existsSync(p)&&fs.statSync(p).isFile());if(!p)throw Error('Import '+id);return load(p);};
 const context={module,exports:module.exports,require:localRequire,console,Date,Intl,URLSearchParams,Response,Request,AbortSignal,AbortController,Blob,File,TextEncoder,TextDecoder,process:{env:{NODE_ENV:'production'}},URL:Object.assign(class extends URL {},{createObjectURL:()=> 'blob:test-only',revokeObjectURL:()=>{}}),setInterval:fn=>{active.intervals.push(fn);return active.intervals.length;},clearInterval:()=>{},setTimeout:()=>1,clearTimeout:()=>{},fetch:(...args)=>active.fetch(...args)};
 for(const name of ['localStorage','sessionStorage','window','document','navigator','history','location'])Object.defineProperty(context,name,{get:()=>active[name]});
 vm.runInNewContext(code,context,{filename:full});return module.exports;
}
const payload=load('lib/content-library.ts').contentPayload();const library=load('lib/content-library.ts');const App=load('components/lahza-app.tsx').default;
function storage(map=new Map()){return {map,getItem:k=>map.has(k)?map.get(k):null,setItem(k,v){if(this.blocked)throw Error('storage denied');map.set(k,String(v));},removeItem:k=>map.delete(k)};}
function expand(n){if(n==null||typeof n==='boolean')return null;if(typeof n!=='object')return String(n);if(Array.isArray(n))return n.map(expand);if(typeof n.type==='function')return expand(n.type(n.props));if(typeof n.type!=='string')return expand(n.props?.children);return {type:n.type,props:n.props,children:expand(n.props.children)};}
function nodes(n){if(!n||typeof n==='string')return [];if(Array.isArray(n))return n.flatMap(nodes);return [n,...nodes(n.children)];}
function text(n){if(n==null)return '';if(typeof n==='string')return n;if(Array.isArray(n))return n.map(text).join('');return text(n.children);}
class Runner{
 constructor({map=new Map(),url='https://test.invalid/',responses=[]}={}){this.hooks=[];this.effects=[];this.intervals=[];this.dirty=true;this.cursor=0;this.localStorage=storage(map);this.sessionStorage=storage();this.location=new URL(url);this.history={replaceState:(_a,_b,p)=>{this.location=new URL(p,this.location);}};this.window={scrollTo:()=>{},confirm:()=>true};this.document={documentElement:{lang:'',dir:''},title:'',createElement:()=>({click:()=>{this.downloaded=true;}})};this.navigator={};this.requests=[];this.responses=responses;this.fetch=async(url,options)=>{if(url.startsWith('/api/content'))return Response.json(payload);const body=JSON.parse(options.body);this.requests.push({url,body});return Response.json(this.responses.length?this.responses.shift():{error:'temporarily_unavailable'},{status:this.responsesStatus||503});};}
 async flush(){for(let turn=0;turn<30;turn++){active=this;if(this.dirty){this.dirty=false;this.cursor=0;this.effects=[];this.tree=expand(App());const effects=[...this.effects];effects.forEach(fn=>fn());}await new Promise(setImmediate);if(!this.dirty)return;}throw Error('Unsettled hooks');}
 all(predicate){return nodes(this.tree).filter(predicate);}
 find(predicate){const found=this.all(predicate);assert.equal(found.length,1,'Expected one target, found '+found.length+'; buttons: '+this.all(n=>n.type==='button').map(n=>text(n)).join(' | '));return found[0];}
 button(label){return this.find(n=>n.type==='button'&&(text(n)===label||n.props['aria-label']===label));}
 async click(label){active=this;const n=this.button(label);assert.ok(!n.props.disabled,'Button disabled: '+label);await n.props.onClick?.();await this.flush();}
 async change(id,value){active=this;const n=this.find(n=>n.props.id===id);n.props.onChange({target:{value,checked:value}});await this.flush();}
 async submit(className){active=this;const n=this.find(n=>n.type==='form'&&n.props.className===className);await n.props.onSubmit({preventDefault(){}});await this.flush();}
 has(s){return text(this.tree).includes(s);}
 async close(){active=this;const n=this.all(n=>n.props['data-close-sheet']);assert.equal(n.length,1);n[0].props.onClick();await this.flush();}
 prefs(){return JSON.parse(this.localStorage.getItem('lahza-prefs-v063'));}
}
const report={version:'0.6.6',at:new Date().toISOString(),scope:'Local execution of actual component event handlers in a controlled hook/storage environment. Not a browser, not visual QA, and no live model calls. Sheet/Switch/Progress primitives are test wrappers. Network failures are injected deliberately.',checks:[],findings:[]};
async function check(name,fn){try{await fn();report.checks.push({name,pass:true});}catch(e){report.checks.push({name,pass:false,error:e.message});}}
let r;
await check('Fresh visitor completes Arabic two-step onboarding with real time default',async()=>{r=new Runner();await r.flush();assert.ok(r.has('اقترب من اللحظة.'));await r.click('متابعة');assert.ok(r.has('لماذا تستخدم لحظة؟'));await r.click('متابعة');assert.equal(r.prefs().onboard,true);assert.equal(r.prefs().mode,'live');assert.ok(r.has('اكتشف معناه'));});
await check('Language changes to English with LTR and persists across reload',async()=>{await r.click('EN');assert.equal(r.document.documentElement.dir,'ltr');const reloaded=new Runner({map:r.localStorage.map});await reloaded.flush();assert.equal(reloaded.prefs().lang,'en');assert.ok(reloaded.has('Discover its meaning'));r=reloaded;});
await check('Pinned preview selection survives reload; Return to now restores live time',async()=>{await r.click('Before sunset');assert.equal(r.prefs().mode,'demo');const a=r.all(n=>n.type==='time').map(text).join();for(const tick of r.intervals)tick();await r.flush();assert.equal(r.all(n=>n.type==='time').map(text).join(),a);const reload=new Runner({map:r.localStorage.map});await reload.flush();assert.equal(reload.prefs().mode,'demo');r=reload;await r.click('Return to now');assert.equal(r.prefs().mode,'live');});
await check('Adhan reader has seven lines and reaches reading step 15',async()=>{await r.click('Discover its meaning');assert.equal(r.all(n=>n.type==='button'&&n.props['data-claim-id']).length,7);for(let i=0;i<14;i++)await r.click('Next phrase');assert.equal(r.button('Next phrase').props.disabled,true);assert.ok(r.has('15 / 15'));await r.close();});
await check('All five moments open with three dimensions and source disclosures',async()=>{for(const label of ['What is that call I can hear?','What are people doing when they pray together?','What happens at Friday noon?','What are people doing before entering?','Is that another call?']){await r.click('Explore');const n=r.all(n=>n.type==='button'&&text(n).includes(label))[0];assert.ok(n);await n.props.onClick();await r.flush();for(const label of ['Spiritual','Values','Character'])assert.ok(r.has(label));const details=r.all(n=>n.type==='details'&&n.props.className==='source-disclosure');assert.ok(details.length>=4);assert.ok(details.every(n=>!n.props.open));const links=r.all(n=>n.type==='a'&&n.props.className==='source-chip');assert.ok(links.length>0&&links.every(n=>n.props.target==='_blank'));}});
await check('Understanding a moment awards one persisted stamp without duplicates',async()=>{await r.click('I understand this moment');let stamps=JSON.parse(r.localStorage.getItem('lahza-passport-v1'));assert.equal(stamps.length,1);await r.click('Explore');const n=r.all(n=>n.type==='button'&&text(n).includes('Is that another call?'))[0];n.props.onClick();await r.flush();await r.click('See your stamp');assert.equal(JSON.parse(r.localStorage.getItem('lahza-passport-v1')).length,1);});
await check('Six-stop journey, wrong and right quiz answers, matching and earned stamp',async()=>{await r.click('Journeys');await r.click('Start the journey');await r.click('I’ve taken a moment');await r.click('Wudu (ablution)');await r.click('Check my choice');assert.ok(r.has('try a different choice'));await r.click('The adhan');await r.click('Check my choice');await r.click('Continue the journey');await r.click('Keep exploring');await r.click('Try making connections');await r.click('Congregational prayer');await r.click('Finish the journey');await r.click('Stamp my passport');const stamps=JSON.parse(r.localStorage.getItem('lahza-passport-v1'));assert.ok(stamps.some(x=>x.id==='journey-call-to-prayer'));assert.equal(JSON.parse(r.localStorage.getItem('lahza-learning-v1')),5);});
await check('Chat failure shows one clear error and no suggested clarification',async()=>{await r.click('Explore');await r.click('I have a question');await r.change('chat-question','What is the spiritual meaning of the adhan?');await r.submit('chat-compose');assert.equal(r.all(n=>n.props.role==='alert').length,1);assert.ok(r.has('The service is unavailable right now. Please try again shortly.'));assert.equal(r.all(n=>n.props.className==='question-button').length,0);});
await check('Retry sends the same request without duplicating the visitor question',async()=>{const before=r.all(n=>n.props.className==='chat-bubble user').length;const payload=r.requests.at(-1).body;await r.click('Try again');assert.equal(r.all(n=>n.props.className==='chat-bubble user').length,before);assert.deepEqual(r.requests.at(-1).body,payload);});
await check('Typed follow-up carries canonical claim IDs from the last answer',async()=>{const claim=library.claims.find(c=>c.claimId==='adhan-purpose');r.responsesStatus=200;r.responses.push({kind:'answer',claims:library.verifySelected([claim.claimId],[claim],'en'),next:[]});await r.change('chat-question','What is the adhan?');await r.submit('chat-compose');r.responses.push({kind:'no_source',claims:[],next:[]});await r.change('chat-question','What does it mean?');await r.submit('chat-compose');assert.deepEqual(r.requests.at(-1).body.context,{question:'What is the adhan?',claimIds:['adhan-purpose']});});
await check('A refusal clears context for the next typed follow-up',async()=>{r.responses.push({kind:'no_source',claims:[],next:[]});await r.change('chat-question','Why?');await r.submit('chat-compose');assert.ok(!r.requests.at(-1).body.context);r.responsesStatus=503;});
await check('Detail refresh restores both moment and selected branch',async()=>{await r.click('Explore');const n=r.all(n=>n.type==='button'&&text(n).includes('What are people doing before entering?'))[0];n.props.onClick();await r.flush();const url=r.location.href;assert.equal(r.location.searchParams.get('moment'),'wudu');assert.ok(r.location.searchParams.get('branch'));const reload=new Runner({map:r.localStorage.map,url});await reload.flush();assert.ok(reload.has('Spiritual'));assert.ok(reload.has('Wudu'));assert.ok(!reload.has('Discover its meaning'));assert.equal(reload.location.href,url);});
await check('Prayer time details also survive refresh',async()=>{const reload=new Runner({map:r.localStorage.map,url:'https://test.invalid/?view=detail&moment=dhuhr&branch=time'});await reload.flush();assert.ok(reload.has('Dhuhr, the midday prayer'));assert.ok(!reload.has('Discover its meaning'));});
await check('Clear data removes stored data and locks later journey stations immediately',async()=>{await r.click('Journeys');await r.click('Start the journey');await r.click('Settings');await r.click('Privacy');await r.click('Clear my data from this device');for(const key of ['lahza-passport-v1','lahza-card-v1','lahza-learning-v1','lahza-visit-interest-v1'])assert.equal(r.localStorage.getItem(key),null);assert.ok(r.has('اقترب من اللحظة.'));await r.click('متابعة');await r.click('متابعة');await r.click('الرحلات');const last=r.all(n=>n.type==='button'&&String(n.props['aria-label']||'').startsWith('ختم رحلتك'))[0];assert.ok(last);assert.equal(last.props.disabled,true);});
await check('Direct judge route bypasses onboarding for a fresh visitor',async()=>{const judge=new Runner({url:'https://test.invalid/judge'});await judge.flush();assert.ok(judge.has('أثر السؤال'));assert.ok(!judge.has('اقترب من اللحظة.'));});
await check('Settings city and iqamah bounds persist',async()=>{await r.click('الإعدادات');await r.change('city','jeddah');assert.equal(r.prefs().city,'jeddah');await r.change('iqamah','999');assert.equal(r.prefs().iqamah,60);await r.change('iqamah','1');assert.equal(r.prefs().iqamah,5);});
await check('Arabic moment cards retain all supplied dimensions and source labels',async()=>{for(const label of ['ما هذا الصوت الذي أسمعه؟','ماذا يفعل المصلون معًا؟','ماذا يحدث ظهر الجمعة؟','ماذا يفعل الناس قبل دخول المسجد؟','هل هذا نداء آخر؟']){await r.click('استكشف');const n=r.all(n=>n.type==='button'&&text(n).includes(label))[0];assert.ok(n);n.props.onClick();await r.flush();for(const label of ['البعد الروحي','البعد القيمي','البعد التربوي'])assert.ok(r.has(label));assert.ok(r.has('للمزيد'));}});
await check('Discovery failure shows the service error without a clarification question',async()=>{await r.click('الآن');await r.click('رأيت أو سمعت شيئًا آخر؟ابدأ بما لفت انتباهك.');await r.click('سمعت صوتًا');await r.change('description','سمعت صوتًا في مكان عام');await r.submit('panel discovery-form');assert.equal(r.requests.at(-1).url,'/api/moments');assert.equal(r.all(n=>n.props.role==='alert').length,1);assert.ok(!r.has('تفصيل صغير يساعدنا'));});
await check('Clear handler race guard aborts and discards late response (handler invoked directly while navigation is disabled)',async()=>{const probe=new Runner({map:new Map([['lahza-prefs-v063',JSON.stringify({lang:'en',onboard:true})]])});await probe.flush();await probe.click('Settings');await probe.click('Privacy');const clearHandler=probe.button('Clear my data from this device').props.onClick;await probe.click('Explore');await probe.click('I have a question');let finish,signal;const oldFetch=probe.fetch;probe.fetch=async(url,options)=>{if(url==='/api/chat'){signal=options.signal;return new Promise(resolve=>{finish=()=>resolve(Response.json({kind:'answer',claims:library.verifySelected(['adhan-purpose'],library.claims,'en'),next:[]}));});}return oldFetch(url,options);};await probe.change('chat-question','What is the adhan?');const request=probe.submit('chat-compose');await probe.flush();assert.ok(signal&&!signal.aborted);assert.equal(probe.button('Settings').props.disabled,true);active=probe;clearHandler();await probe.flush();assert.equal(signal.aborted,true);finish();await request;assert.ok(probe.has('اقترب من اللحظة.'));assert.equal(probe.localStorage.getItem('lahza-impact-v060'),null);await probe.click('متابعة');await probe.click('متابعة');await probe.click('استكشف');await probe.click('لدي سؤال');assert.equal(probe.all(n=>n.props.className==='chat-bubble assistant').length,0);});
report.summary={checks:report.checks.length,passed:report.checks.filter(c=>c.pass).length,failed:report.checks.filter(c=>!c.pass).length,findings:report.findings.length};fs.writeFileSync(out+'/component-interactions.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));

process.exitCode=report.summary.failed?1:0;
